-- =========================================================================
-- GENERATED FILE - DO NOT EDIT.
-- Source : config/tag_catalog.yaml
-- Rebuild: make build   (scripts/generate_sql.py)
-- CI fails if this file differs from a fresh generation.
-- =========================================================================


-- -----------------------------------------------------------------------------
-- Full refresh of the tag registry from the catalog.
-- Wrapped in a transaction so the registry is never observed half-loaded by the
-- validation task, which reads these tables on a schedule.
-- -----------------------------------------------------------------------------

USE ROLE TAG_ADMIN;
USE WAREHOUSE GOVERNANCE_WH;
USE DATABASE GOVERNANCE;
USE SCHEMA CONTROL;

BEGIN TRANSACTION;

DELETE FROM TAG_REQUIREMENT;
DELETE FROM TAG_ALLOWED_VALUE;
DELETE FROM TAG_POLICY_BINDING;
DELETE FROM TAG_CONDITIONAL_RULE;
DELETE FROM REGULATION_PRECEDENCE;
DELETE FROM TAG_CATALOG;

-- TAG_CATALOG
INSERT INTO TAG_CATALOG (TAG_NAME, TIER, CATEGORY, DESCRIPTION, VALUE_SOURCE, VALUE_FORMAT_REGEX, REFERENCE_SET, INHERITANCE_MODE, OVERRIDE_RULE, ORDINAL_VALUES, DRIVES, OWNER_ROLE, TAG_VERSION, STATUS, DEPRECATES, CATALOG_VERSION)
SELECT c1, c2::NUMBER(1,0), c3, c4, c5, c6, c7, c8, c9, PARSE_JSON(c10)::ARRAY, PARSE_JSON(c11)::ARRAY, c12, c13, c14, c15, c16
FROM VALUES
    ('BUSINESS_UNIT', 1, 'business', 'Top-level legal/reporting entity accountable for the object. Anchors cost allocation, access boundaries and regulatory jurisdiction.', 'reference_data', '^[A-Z0-9][A-Z0-9_]{1,62}$', 'REF_BUSINESS_UNIT', 'inherit', 'any', NULL, '["finops_chargeback", "access_boundary", "discovery", "compliance_reporting"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DOMAIN', 1, 'business', 'Data Mesh domain that owns the object (e.g. CUSTOMER, FINANCE, SUPPLY_CHAIN). The unit of federated governance and of data-product publication.', 'reference_data', '^[A-Z0-9][A-Z0-9_]{1,62}$', 'REF_DOMAIN', 'inherit', 'any', NULL, '["data_mesh", "discovery", "federated_governance", "finops_showback"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DATA_PRODUCT', 1, 'business', 'Named, versioned, independently consumable data product. In this framework a data product maps 1:1 to a schema (the publication boundary).', 'reference_data', '^[A-Z0-9][A-Z0-9_]{2,62}$', 'REF_DATA_PRODUCT', 'inherit', 'none', NULL, '["data_mesh", "discovery", "lineage", "sla_management", "finops_showback"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DATA_OWNER', 1, 'ownership', 'Accountable business owner (RACI ''A'') for the data. Named individual or enterprise group. Approves access, classification and retention decisions.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|GRP-[A-Z0-9-]{3,48})$', NULL, 'inherit', 'any', NULL, '["access_approval", "incident_routing", "attestation", "discovery"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DATA_STEWARD', 1, 'ownership', 'Responsible steward (RACI ''R'') executing day-to-day governance: tagging, classification review, quality remediation, metadata curation.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|GRP-[A-Z0-9-]{3,48})$', NULL, 'inherit', 'any', NULL, '["stewardship_workflow", "attestation", "remediation_routing"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('SUPPORT_GROUP', 1, 'ownership', 'Operational on-call group that owns break/fix for the object. Must resolve to a real queue in the enterprise ITSM tool.', 'reference_data', '^GRP-[A-Z0-9-]{3,48}$', 'REF_SUPPORT_GROUP', 'inherit', 'any', NULL, '["incident_routing", "sla_management", "operational_reporting"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DATA_CLASSIFICATION', 1, 'classification', 'Enterprise confidentiality level. The primary driver of masking, sharing eligibility and export controls. Most restrictive value in the lineage wins.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED", "HIGHLY_RESTRICTED"]', '["dynamic_masking", "sharing_control", "export_control", "compliance_reporting", "discovery"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('PII', 1, 'privacy', 'Object contains Personally Identifiable Information as defined by the enterprise privacy standard. Set automatically at column level by the Snowflake classification reconciliation job; human-overridable with reason.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["dynamic_masking", "privacy_reporting", "dsar_fulfilment", "gdpr_ccpa_evidence", "auto_classification"]', 'PRIVACY_OFFICE', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('ENVIRONMENT', 1, 'lifecycle', 'Deployment environment of the object. Never inherited across a clone into a different environment - the clone-remediation task rewrites it.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'none', NULL, '["policy_selection", "finops_chargeback", "promotion_gate", "masking_strictness"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DATA_LIFECYCLE', 1, 'lifecycle', 'Lifecycle state of the object itself. Drives deprecation comms, consumer warnings and the automated archive/purge pipeline.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["retirement_automation", "consumer_notification", "cost_avoidance", "discovery"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('CRITICALITY', 1, 'lifecycle', 'Business impact if the object is unavailable or incorrect. Drives DR scope, monitoring depth, change-control rigour and incident severity.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["LOW", "MEDIUM", "HIGH", "CRITICAL"]', '["dr_scope", "monitoring_depth", "change_control", "incident_severity"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('COST_CENTER', 1, 'financial', 'GL cost centre charged for the compute and storage attributed to the object. Must exist and be open in the ERP chart of accounts.', 'reference_data', '^CC-[0-9]{4,8}$', 'REF_COST_CENTER', 'inherit', 'any', NULL, '["finops_chargeback", "budget_enforcement", "department_reporting"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('RETENTION_CLASS', 1, 'compliance', 'Records-management retention class from the enterprise retention schedule. Drives the automated archive/purge pipeline. LEGAL_HOLD always supersedes.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["retention_automation", "purge_pipeline", "compliance_reporting", "storage_cost_control"]', 'RECORDS_MANAGEMENT', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('REGULATION', 1, 'compliance', 'The GOVERNING regulatory regime - the single regime whose controls are the most stringent for this object, resolved by documented precedence. The full multi-regime scope lives in CONTROL.REGULATORY_SCOPE (Snowflake tags are single-valued); see docs/02-tag-taxonomy.md#multi-valued-attributes.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["compliance_reporting", "residency_control", "audit_evidence", "policy_selection"]', 'COMPLIANCE_OFFICE', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('MASKING_REQUIRED', 1, 'security', 'Declares that the column must carry a masking policy. This is the DECLARED INTENT; SNOWFLAKE.CORE tag-based masking attachment is the ENFORCEMENT. The drift detector reconciles the two and raises on divergence.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["dynamic_masking", "control_attestation", "drift_detection"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('ROW_ACCESS_REQUIRED', 1, 'security', 'Declares that the table/view must carry a row access policy. Snowflake does NOT support attaching row access policies to tags, so enforcement is via the SP_APPLY_ROW_ACCESS_POLICIES reconciliation task, not tag attachment.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["row_access_policy", "control_attestation", "drift_detection"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('SLA_TIER', 1, 'operational', 'Freshness/availability commitment published to consumers of the data product. Drives monitoring thresholds, alert routing and DR tiering.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', '["BEST_EFFORT", "BRONZE_24H", "SILVER_4H", "GOLD_1H", "PLATINUM_15M"]', '["sla_management", "monitoring_depth", "alert_routing", "dr_scope"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('SUB_DOMAIN', 2, 'business', 'Second-level decomposition of DOMAIN, for large domains only.', 'reference_data', '^[A-Z0-9][A-Z0-9_]{1,62}$', 'REF_SUB_DOMAIN', 'inherit', 'any', NULL, '["discovery", "federated_governance", "finops_showback"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('APPLICATION', 2, 'business', 'CMDB application identifier of the producing or consuming system. Enables impact analysis between Snowflake objects and the application portfolio.', 'reference_data', '^APP-[0-9]{4,8}$', 'REF_APPLICATION', 'inherit', 'any', NULL, '["impact_analysis", "cmdb_reconciliation", "incident_routing"]', 'ENTERPRISE_ARCHITECTURE', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('APPLICATION_OWNER', 2, 'ownership', 'Accountable owner of the APPLICATION referenced by the object.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|GRP-[A-Z0-9-]{3,48})$', NULL, 'inherit', 'any', NULL, '["impact_analysis", "incident_routing", "attestation"]', 'ENTERPRISE_ARCHITECTURE', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('PLATFORM_OWNER', 2, 'ownership', 'Platform engineering team accountable for the Snowflake infrastructure object (warehouse, integration, share, account-level construct).', 'reference_data', '^GRP-[A-Z0-9-]{3,48}$', 'REF_SUPPORT_GROUP', 'inherit', 'any', NULL, '["incident_routing", "platform_attestation", "finops_chargeback"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DOMAIN_OWNER', 2, 'data_mesh', 'Accountable owner of the mesh DOMAIN. Normally set once on the domain''s database and inherited; a per-object override is an exception.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|GRP-[A-Z0-9-]{3,48})$', NULL, 'inherit', 'any', NULL, '["data_mesh", "federated_governance", "access_approval"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DATA_PRODUCT_OWNER', 2, 'data_mesh', 'Product owner accountable for the data product''s roadmap, SLA and consumer contract. Distinct from DATA_OWNER (who is accountable for the data itself).', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|GRP-[A-Z0-9-]{3,48})$', NULL, 'inherit', 'any', NULL, '["data_mesh", "sla_management", "consumer_contract", "access_approval"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DATA_PRODUCT_TYPE', 2, 'data_mesh', 'Mesh archetype of the data product; sets default quality and SLA expectations.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["data_mesh", "discovery", "quality_expectation"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('PHI', 2, 'privacy', 'Protected Health Information under HIPAA. Conditionally MANDATORY wherever REGULATION resolves to HIPAA. Drives the HIPAA masking policy set.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["dynamic_masking", "hipaa_evidence", "privacy_reporting", "auto_classification"]', 'PRIVACY_OFFICE', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('PCI', 2, 'privacy', 'Cardholder data in PCI-DSS scope. Conditionally MANDATORY wherever REGULATION resolves to PCI_DSS. Drives tokenisation/masking and CDE scoping.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["dynamic_masking", "pci_scoping", "audit_evidence", "auto_classification"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('LEGAL_HOLD', 2, 'compliance', 'Litigation hold. When YES, all retention-driven archive and purge automation is suppressed regardless of RETENTION_CLASS. Set only by Legal.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["purge_suppression", "ediscovery", "audit_evidence"]', 'LEGAL', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('ENCRYPTION_REQUIRED', 2, 'security', 'Declares that application-layer or client-side encryption is required in addition to Snowflake''s transparent encryption at rest. Applies mainly to external stages and to columns holding secrets or key material.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["encryption_control", "audit_evidence", "drift_detection"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DATA_QUALITY_TIER', 2, 'data_quality', 'Certified quality level of the object. Set only by the data-quality pipeline after DMF results are evaluated; manual promotion requires an exception.', 'controlled_vocabulary', NULL, NULL, 'explicit_only', 'any', '["BRONZE", "SILVER", "GOLD", "PLATINUM"]', '["quality_reporting", "consumer_contract", "discovery", "certification"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('REFRESH_TYPE', 2, 'operational', 'How the object''s data is refreshed. Drives freshness monitoring logic.', 'controlled_vocabulary', NULL, NULL, 'explicit_only', 'any', NULL, '["freshness_monitoring", "sla_management", "lineage"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('PROJECT_CODE', 2, 'financial', 'Capital or programme project funding the workload. Enables project-level cost attribution separate from the steady-state COST_CENTER.', 'reference_data', '^(PRJ|PRG)-[A-Z0-9]{2,4}-[0-9]{3,6}$', 'REF_PROJECT', 'inherit', 'any', NULL, '["finops_chargeback", "project_reporting", "capitalisation"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('CAPABILITY', 3, 'business', 'Business capability from the enterprise capability model (L2).', 'reference_data', '^[A-Z0-9][A-Z0-9_]{1,62}$', 'REF_CAPABILITY', 'inherit', 'any', NULL, '["discovery", "portfolio_analysis"]', 'ENTERPRISE_ARCHITECTURE', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('SOURCE_SYSTEM', 3, 'business', 'System of record from which the data originates. Supports lineage rooting.', 'reference_data', '^APP-[0-9]{4,8}$', 'REF_APPLICATION', 'inherit', 'any', NULL, '["lineage", "impact_analysis", "discovery"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('DATA_RESIDENCY', 3, 'compliance', 'ISO-3166 region in which the data must remain. Drives replication and cross-region share eligibility checks.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["residency_control", "replication_control", "sharing_control", "compliance_reporting"]', 'COMPLIANCE_OFFICE', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('SENSITIVE_DATA', 3, 'privacy', 'Special-category / sensitive data beyond PII (e.g. biometric, union membership, religion, sexual orientation) per GDPR Art. 9.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["dynamic_masking", "privacy_reporting", "gdpr_ccpa_evidence"]', 'PRIVACY_OFFICE', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('PROGRAM', 3, 'financial', 'Multi-project programme rollup for executive cost reporting.', 'reference_data', '^PRG-[A-Z0-9]{2,4}-[0-9]{3,6}$', 'REF_PROJECT', 'inherit', 'any', NULL, '["finops_chargeback", "project_reporting"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('PRODUCT_CODE', 3, 'financial', 'Commercial product/SKU whose P&L the workload supports.', 'reference_data', '^[A-Z0-9][A-Z0-9_]{1,62}$', 'REF_PRODUCT', 'inherit', 'any', NULL, '["finops_chargeback", "product_pnl"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('PRODUCT_OWNER', 3, 'ownership', 'Commercial owner of the PRODUCT_CODE. Distinct from DATA_PRODUCT_OWNER.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|GRP-[A-Z0-9-]{3,48})$', NULL, 'inherit', 'any', NULL, '["product_pnl", "access_approval"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('RPO', 3, 'operational', 'Recovery Point Objective as an ISO-8601 duration (e.g. PT15M, P1D).', 'free_text', '^PT(?:[0-9]{1,3}H)?(?:[0-9]{1,3}M)?$|^P[0-9]{1,3}D$', NULL, 'inherit', 'any', NULL, '["dr_scope", "replication_control", "sla_management"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('RTO', 3, 'operational', 'Recovery Time Objective as an ISO-8601 duration (e.g. PT4H, P1D).', 'free_text', '^PT(?:[0-9]{1,3}H)?(?:[0-9]{1,3}M)?$|^P[0-9]{1,3}D$', NULL, 'inherit', 'any', NULL, '["dr_scope", "sla_management"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('SHARING_SCOPE', 3, 'security', 'Maximum permitted distribution of the object. Checked before any listing, share or reader-account grant is created.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', '["PROHIBITED", "INTERNAL_ONLY", "AFFILIATE", "PARTNER", "PUBLIC_MARKETPLACE"]', '["sharing_control", "export_control", "compliance_reporting"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '1.0.0'),
    ('COST_ALLOCATION_MODEL', 3, 'financial', 'How this object''s consumption is settled with the business. SHOWBACK reports only; CHARGEBACK posts a journal entry to the ERP.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["finops_chargeback", "department_reporting"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '1.0.0')
AS v(c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16);


-- TAG_ALLOWED_VALUE
INSERT INTO TAG_ALLOWED_VALUE (TAG_NAME, TAG_VALUE, ORDINAL_POSITION)
SELECT c1, c2, c3::NUMBER(5,0)
FROM VALUES
    ('DATA_CLASSIFICATION', 'PUBLIC', 1),
    ('DATA_CLASSIFICATION', 'INTERNAL', 2),
    ('DATA_CLASSIFICATION', 'CONFIDENTIAL', 3),
    ('DATA_CLASSIFICATION', 'RESTRICTED', 4),
    ('DATA_CLASSIFICATION', 'HIGHLY_RESTRICTED', 5),
    ('PII', 'YES', 2),
    ('PII', 'NO', 1),
    ('ENVIRONMENT', 'DEV', NULL),
    ('ENVIRONMENT', 'TEST', NULL),
    ('ENVIRONMENT', 'UAT', NULL),
    ('ENVIRONMENT', 'PROD', NULL),
    ('ENVIRONMENT', 'SANDBOX', NULL),
    ('ENVIRONMENT', 'DR', NULL),
    ('DATA_LIFECYCLE', 'ACTIVE', NULL),
    ('DATA_LIFECYCLE', 'DEPRECATED', NULL),
    ('DATA_LIFECYCLE', 'ARCHIVED', NULL),
    ('DATA_LIFECYCLE', 'PENDING_PURGE', NULL),
    ('CRITICALITY', 'LOW', 1),
    ('CRITICALITY', 'MEDIUM', 2),
    ('CRITICALITY', 'HIGH', 3),
    ('CRITICALITY', 'CRITICAL', 4),
    ('RETENTION_CLASS', 'TRANSIENT_30D', NULL),
    ('RETENTION_CLASS', 'SHORT_1Y', NULL),
    ('RETENTION_CLASS', 'STANDARD_3Y', NULL),
    ('RETENTION_CLASS', 'EXTENDED_7Y', NULL),
    ('RETENTION_CLASS', 'REGULATORY_10Y', NULL),
    ('RETENTION_CLASS', 'PERMANENT', NULL),
    ('RETENTION_CLASS', 'INDEFINITE_REVIEW', NULL),
    ('REGULATION', 'NONE', NULL),
    ('REGULATION', 'SOX', NULL),
    ('REGULATION', 'GDPR', NULL),
    ('REGULATION', 'CCPA', NULL),
    ('REGULATION', 'HIPAA', NULL),
    ('REGULATION', 'PCI_DSS', NULL),
    ('REGULATION', 'GLBA', NULL),
    ('REGULATION', 'FERPA', NULL),
    ('REGULATION', 'LGPD', NULL),
    ('REGULATION', 'PIPEDA', NULL),
    ('REGULATION', 'PDPA', NULL),
    ('REGULATION', 'MULTI', NULL),
    ('MASKING_REQUIRED', 'YES', 2),
    ('MASKING_REQUIRED', 'NO', 1),
    ('ROW_ACCESS_REQUIRED', 'YES', 2),
    ('ROW_ACCESS_REQUIRED', 'NO', 1),
    ('SLA_TIER', 'PLATINUM_15M', 5),
    ('SLA_TIER', 'GOLD_1H', 4),
    ('SLA_TIER', 'SILVER_4H', 3),
    ('SLA_TIER', 'BRONZE_24H', 2),
    ('SLA_TIER', 'BEST_EFFORT', 1),
    ('DATA_PRODUCT_TYPE', 'SOURCE_ALIGNED', NULL),
    ('DATA_PRODUCT_TYPE', 'AGGREGATE', NULL),
    ('DATA_PRODUCT_TYPE', 'CONSUMER_ALIGNED', NULL),
    ('DATA_PRODUCT_TYPE', 'SHARED', NULL),
    ('DATA_PRODUCT_TYPE', 'PLATFORM', NULL),
    ('PHI', 'YES', 2),
    ('PHI', 'NO', 1),
    ('PCI', 'YES', 2),
    ('PCI', 'NO', 1),
    ('LEGAL_HOLD', 'YES', 2),
    ('LEGAL_HOLD', 'NO', 1),
    ('ENCRYPTION_REQUIRED', 'YES', 2),
    ('ENCRYPTION_REQUIRED', 'NO', 1),
    ('DATA_QUALITY_TIER', 'BRONZE', 1),
    ('DATA_QUALITY_TIER', 'SILVER', 2),
    ('DATA_QUALITY_TIER', 'GOLD', 3),
    ('DATA_QUALITY_TIER', 'PLATINUM', 4),
    ('REFRESH_TYPE', 'STREAMING', NULL),
    ('REFRESH_TYPE', 'MICRO_BATCH', NULL),
    ('REFRESH_TYPE', 'BATCH_HOURLY', NULL),
    ('REFRESH_TYPE', 'BATCH_DAILY', NULL),
    ('REFRESH_TYPE', 'BATCH_WEEKLY', NULL),
    ('REFRESH_TYPE', 'BATCH_MONTHLY', NULL),
    ('REFRESH_TYPE', 'ON_DEMAND', NULL),
    ('REFRESH_TYPE', 'STATIC', NULL),
    ('DATA_RESIDENCY', 'GLOBAL', NULL),
    ('DATA_RESIDENCY', 'US', NULL),
    ('DATA_RESIDENCY', 'EU', NULL),
    ('DATA_RESIDENCY', 'UK', NULL),
    ('DATA_RESIDENCY', 'APAC', NULL),
    ('DATA_RESIDENCY', 'CANADA', NULL),
    ('DATA_RESIDENCY', 'LATAM', NULL),
    ('DATA_RESIDENCY', 'CHINA', NULL),
    ('DATA_RESIDENCY', 'INDIA', NULL),
    ('DATA_RESIDENCY', 'JAPAN', NULL),
    ('DATA_RESIDENCY', 'AUSTRALIA', NULL),
    ('SENSITIVE_DATA', 'YES', 2),
    ('SENSITIVE_DATA', 'NO', 1),
    ('SHARING_SCOPE', 'INTERNAL_ONLY', 2),
    ('SHARING_SCOPE', 'AFFILIATE', 3),
    ('SHARING_SCOPE', 'PARTNER', 4),
    ('SHARING_SCOPE', 'PUBLIC_MARKETPLACE', 5),
    ('SHARING_SCOPE', 'PROHIBITED', 1),
    ('COST_ALLOCATION_MODEL', 'SHOWBACK', NULL),
    ('COST_ALLOCATION_MODEL', 'CHARGEBACK', NULL),
    ('COST_ALLOCATION_MODEL', 'SHARED_SERVICE', NULL),
    ('COST_ALLOCATION_MODEL', 'ABSORBED_PLATFORM', NULL)
AS v(c1, c2, c3);


-- TAG_REQUIREMENT
INSERT INTO TAG_REQUIREMENT (TAG_NAME, OBJECT_TYPE, REQUIREMENT_LEVEL)
SELECT c1, c2, c3
FROM VALUES
    ('BUSINESS_UNIT', 'ACCOUNT', 'INHERITED'),
    ('BUSINESS_UNIT', 'DATABASE', 'MANDATORY'),
    ('BUSINESS_UNIT', 'SCHEMA', 'INHERITED'),
    ('BUSINESS_UNIT', 'TABLE', 'INHERITED'),
    ('BUSINESS_UNIT', 'VIEW', 'INHERITED'),
    ('BUSINESS_UNIT', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('BUSINESS_UNIT', 'DYNAMIC_TABLE', 'INHERITED'),
    ('BUSINESS_UNIT', 'STAGE', 'INHERITED'),
    ('BUSINESS_UNIT', 'PIPE', 'INHERITED'),
    ('BUSINESS_UNIT', 'TASK', 'INHERITED'),
    ('BUSINESS_UNIT', 'STREAM', 'INHERITED'),
    ('BUSINESS_UNIT', 'WAREHOUSE', 'MANDATORY'),
    ('BUSINESS_UNIT', 'ROLE', 'INHERITED'),
    ('BUSINESS_UNIT', 'NOTEBOOK', 'INHERITED'),
    ('BUSINESS_UNIT', 'STREAMLIT', 'INHERITED'),
    ('BUSINESS_UNIT', 'APPLICATION', 'INHERITED'),
    ('DOMAIN', 'DATABASE', 'MANDATORY'),
    ('DOMAIN', 'SCHEMA', 'MANDATORY'),
    ('DOMAIN', 'TABLE', 'INHERITED'),
    ('DOMAIN', 'VIEW', 'INHERITED'),
    ('DOMAIN', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DOMAIN', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DOMAIN', 'STAGE', 'INHERITED'),
    ('DOMAIN', 'PIPE', 'INHERITED'),
    ('DOMAIN', 'TASK', 'INHERITED'),
    ('DOMAIN', 'STREAM', 'INHERITED'),
    ('DOMAIN', 'WAREHOUSE', 'INHERITED'),
    ('DOMAIN', 'NOTEBOOK', 'INHERITED'),
    ('DOMAIN', 'STREAMLIT', 'INHERITED'),
    ('DOMAIN', 'APPLICATION', 'INHERITED'),
    ('DATA_PRODUCT', 'SCHEMA', 'MANDATORY'),
    ('DATA_PRODUCT', 'TABLE', 'INHERITED'),
    ('DATA_PRODUCT', 'VIEW', 'INHERITED'),
    ('DATA_PRODUCT', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_PRODUCT', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_PRODUCT', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_PRODUCT', 'STAGE', 'INHERITED'),
    ('DATA_PRODUCT', 'PIPE', 'INHERITED'),
    ('DATA_PRODUCT', 'TASK', 'INHERITED'),
    ('DATA_PRODUCT', 'STREAM', 'INHERITED'),
    ('DATA_PRODUCT', 'SHARE', 'MANDATORY'),
    ('DATA_PRODUCT', 'NOTEBOOK', 'INHERITED'),
    ('DATA_PRODUCT', 'STREAMLIT', 'INHERITED'),
    ('DATA_OWNER', 'DATABASE', 'MANDATORY'),
    ('DATA_OWNER', 'SCHEMA', 'MANDATORY'),
    ('DATA_OWNER', 'TABLE', 'INHERITED'),
    ('DATA_OWNER', 'VIEW', 'INHERITED'),
    ('DATA_OWNER', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_OWNER', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_OWNER', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_OWNER', 'STAGE', 'INHERITED'),
    ('DATA_OWNER', 'SHARE', 'INHERITED'),
    ('DATA_OWNER', 'APPLICATION', 'INHERITED'),
    ('DATA_STEWARD', 'DATABASE', 'INHERITED'),
    ('DATA_STEWARD', 'SCHEMA', 'MANDATORY'),
    ('DATA_STEWARD', 'TABLE', 'INHERITED'),
    ('DATA_STEWARD', 'VIEW', 'INHERITED'),
    ('DATA_STEWARD', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_STEWARD', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_STEWARD', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_STEWARD', 'STAGE', 'INHERITED'),
    ('SUPPORT_GROUP', 'DATABASE', 'MANDATORY'),
    ('SUPPORT_GROUP', 'SCHEMA', 'INHERITED'),
    ('SUPPORT_GROUP', 'TABLE', 'INHERITED'),
    ('SUPPORT_GROUP', 'VIEW', 'INHERITED'),
    ('SUPPORT_GROUP', 'DYNAMIC_TABLE', 'INHERITED'),
    ('SUPPORT_GROUP', 'STAGE', 'INHERITED'),
    ('SUPPORT_GROUP', 'PIPE', 'MANDATORY'),
    ('SUPPORT_GROUP', 'TASK', 'MANDATORY'),
    ('SUPPORT_GROUP', 'STREAM', 'INHERITED'),
    ('SUPPORT_GROUP', 'WAREHOUSE', 'INHERITED'),
    ('SUPPORT_GROUP', 'APPLICATION', 'INHERITED'),
    ('DATA_CLASSIFICATION', 'ACCOUNT', 'INHERITED'),
    ('DATA_CLASSIFICATION', 'DATABASE', 'MANDATORY'),
    ('DATA_CLASSIFICATION', 'SCHEMA', 'MANDATORY'),
    ('DATA_CLASSIFICATION', 'TABLE', 'MANDATORY'),
    ('DATA_CLASSIFICATION', 'VIEW', 'MANDATORY'),
    ('DATA_CLASSIFICATION', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_CLASSIFICATION', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_CLASSIFICATION', 'EXTERNAL_TABLE', 'INHERITED'),
    ('DATA_CLASSIFICATION', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_CLASSIFICATION', 'COLUMN', 'RECOMMENDED'),
    ('DATA_CLASSIFICATION', 'STAGE', 'MANDATORY'),
    ('DATA_CLASSIFICATION', 'SHARE', 'MANDATORY'),
    ('DATA_CLASSIFICATION', 'NOTEBOOK', 'INHERITED'),
    ('DATA_CLASSIFICATION', 'STREAMLIT', 'INHERITED'),
    ('PII', 'DATABASE', 'INHERITED'),
    ('PII', 'SCHEMA', 'RECOMMENDED'),
    ('PII', 'TABLE', 'MANDATORY'),
    ('PII', 'VIEW', 'MANDATORY'),
    ('PII', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('PII', 'DYNAMIC_TABLE', 'INHERITED'),
    ('PII', 'EXTERNAL_TABLE', 'INHERITED'),
    ('PII', 'ICEBERG_TABLE', 'INHERITED'),
    ('PII', 'COLUMN', 'MANDATORY'),
    ('PII', 'STAGE', 'INHERITED'),
    ('PII', 'SHARE', 'MANDATORY'),
    ('ENVIRONMENT', 'ACCOUNT', 'INHERITED'),
    ('ENVIRONMENT', 'DATABASE', 'MANDATORY'),
    ('ENVIRONMENT', 'SCHEMA', 'INHERITED'),
    ('ENVIRONMENT', 'STAGE', 'INHERITED'),
    ('ENVIRONMENT', 'PIPE', 'INHERITED'),
    ('ENVIRONMENT', 'TASK', 'INHERITED'),
    ('ENVIRONMENT', 'STREAM', 'INHERITED'),
    ('ENVIRONMENT', 'WAREHOUSE', 'MANDATORY'),
    ('ENVIRONMENT', 'ROLE', 'INHERITED'),
    ('ENVIRONMENT', 'INTEGRATION', 'INHERITED'),
    ('ENVIRONMENT', 'NOTEBOOK', 'INHERITED'),
    ('ENVIRONMENT', 'STREAMLIT', 'INHERITED'),
    ('ENVIRONMENT', 'APPLICATION', 'INHERITED'),
    ('DATA_LIFECYCLE', 'DATABASE', 'INHERITED'),
    ('DATA_LIFECYCLE', 'SCHEMA', 'MANDATORY'),
    ('DATA_LIFECYCLE', 'TABLE', 'MANDATORY'),
    ('DATA_LIFECYCLE', 'VIEW', 'MANDATORY'),
    ('DATA_LIFECYCLE', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_LIFECYCLE', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_LIFECYCLE', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_LIFECYCLE', 'STAGE', 'INHERITED'),
    ('DATA_LIFECYCLE', 'PIPE', 'INHERITED'),
    ('DATA_LIFECYCLE', 'TASK', 'INHERITED'),
    ('DATA_LIFECYCLE', 'STREAM', 'INHERITED'),
    ('DATA_LIFECYCLE', 'SHARE', 'INHERITED'),
    ('CRITICALITY', 'DATABASE', 'MANDATORY'),
    ('CRITICALITY', 'SCHEMA', 'MANDATORY'),
    ('CRITICALITY', 'TABLE', 'INHERITED'),
    ('CRITICALITY', 'VIEW', 'INHERITED'),
    ('CRITICALITY', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('CRITICALITY', 'DYNAMIC_TABLE', 'INHERITED'),
    ('CRITICALITY', 'PIPE', 'INHERITED'),
    ('CRITICALITY', 'TASK', 'INHERITED'),
    ('CRITICALITY', 'STREAM', 'INHERITED'),
    ('CRITICALITY', 'WAREHOUSE', 'INHERITED'),
    ('CRITICALITY', 'APPLICATION', 'INHERITED'),
    ('COST_CENTER', 'ACCOUNT', 'INHERITED'),
    ('COST_CENTER', 'DATABASE', 'MANDATORY'),
    ('COST_CENTER', 'SCHEMA', 'INHERITED'),
    ('COST_CENTER', 'PIPE', 'INHERITED'),
    ('COST_CENTER', 'TASK', 'INHERITED'),
    ('COST_CENTER', 'WAREHOUSE', 'MANDATORY'),
    ('COST_CENTER', 'ROLE', 'INHERITED'),
    ('COST_CENTER', 'USER', 'INHERITED'),
    ('COST_CENTER', 'NOTEBOOK', 'INHERITED'),
    ('COST_CENTER', 'STREAMLIT', 'INHERITED'),
    ('COST_CENTER', 'APPLICATION', 'INHERITED'),
    ('RETENTION_CLASS', 'DATABASE', 'INHERITED'),
    ('RETENTION_CLASS', 'SCHEMA', 'MANDATORY'),
    ('RETENTION_CLASS', 'TABLE', 'MANDATORY'),
    ('RETENTION_CLASS', 'VIEW', 'INHERITED'),
    ('RETENTION_CLASS', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('RETENTION_CLASS', 'DYNAMIC_TABLE', 'INHERITED'),
    ('RETENTION_CLASS', 'EXTERNAL_TABLE', 'INHERITED'),
    ('RETENTION_CLASS', 'ICEBERG_TABLE', 'INHERITED'),
    ('RETENTION_CLASS', 'STAGE', 'MANDATORY'),
    ('REGULATION', 'DATABASE', 'INHERITED'),
    ('REGULATION', 'SCHEMA', 'MANDATORY'),
    ('REGULATION', 'TABLE', 'MANDATORY'),
    ('REGULATION', 'VIEW', 'INHERITED'),
    ('REGULATION', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('REGULATION', 'DYNAMIC_TABLE', 'INHERITED'),
    ('REGULATION', 'EXTERNAL_TABLE', 'INHERITED'),
    ('REGULATION', 'ICEBERG_TABLE', 'INHERITED'),
    ('REGULATION', 'COLUMN', 'OPTIONAL'),
    ('REGULATION', 'STAGE', 'INHERITED'),
    ('REGULATION', 'SHARE', 'MANDATORY'),
    ('MASKING_REQUIRED', 'TABLE', 'RECOMMENDED'),
    ('MASKING_REQUIRED', 'VIEW', 'RECOMMENDED'),
    ('MASKING_REQUIRED', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('MASKING_REQUIRED', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('MASKING_REQUIRED', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('MASKING_REQUIRED', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('MASKING_REQUIRED', 'COLUMN', 'MANDATORY'),
    ('ROW_ACCESS_REQUIRED', 'TABLE', 'MANDATORY'),
    ('ROW_ACCESS_REQUIRED', 'VIEW', 'MANDATORY'),
    ('ROW_ACCESS_REQUIRED', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('ROW_ACCESS_REQUIRED', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('ROW_ACCESS_REQUIRED', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('ROW_ACCESS_REQUIRED', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('SLA_TIER', 'SCHEMA', 'MANDATORY'),
    ('SLA_TIER', 'TABLE', 'INHERITED'),
    ('SLA_TIER', 'VIEW', 'INHERITED'),
    ('SLA_TIER', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('SLA_TIER', 'DYNAMIC_TABLE', 'INHERITED'),
    ('SLA_TIER', 'PIPE', 'MANDATORY'),
    ('SLA_TIER', 'TASK', 'MANDATORY'),
    ('SLA_TIER', 'STREAM', 'INHERITED'),
    ('SLA_TIER', 'SHARE', 'INHERITED'),
    ('SUB_DOMAIN', 'SCHEMA', 'RECOMMENDED'),
    ('SUB_DOMAIN', 'TABLE', 'OPTIONAL'),
    ('SUB_DOMAIN', 'VIEW', 'OPTIONAL'),
    ('SUB_DOMAIN', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('SUB_DOMAIN', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('SUB_DOMAIN', 'PIPE', 'OPTIONAL'),
    ('SUB_DOMAIN', 'TASK', 'OPTIONAL'),
    ('SUB_DOMAIN', 'STREAM', 'OPTIONAL'),
    ('APPLICATION', 'DATABASE', 'OPTIONAL'),
    ('APPLICATION', 'SCHEMA', 'RECOMMENDED'),
    ('APPLICATION', 'TABLE', 'OPTIONAL'),
    ('APPLICATION', 'VIEW', 'OPTIONAL'),
    ('APPLICATION', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('APPLICATION', 'STAGE', 'OPTIONAL'),
    ('APPLICATION', 'PIPE', 'RECOMMENDED'),
    ('APPLICATION', 'TASK', 'OPTIONAL'),
    ('APPLICATION', 'STREAM', 'OPTIONAL'),
    ('APPLICATION', 'INTEGRATION', 'RECOMMENDED'),
    ('APPLICATION', 'NOTEBOOK', 'OPTIONAL'),
    ('APPLICATION', 'STREAMLIT', 'OPTIONAL'),
    ('APPLICATION', 'APPLICATION', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'DATABASE', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'SCHEMA', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'STAGE', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'PIPE', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'TASK', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'INTEGRATION', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'APPLICATION', 'RECOMMENDED'),
    ('PLATFORM_OWNER', 'ACCOUNT', 'OPTIONAL'),
    ('PLATFORM_OWNER', 'DATABASE', 'OPTIONAL'),
    ('PLATFORM_OWNER', 'WAREHOUSE', 'MANDATORY'),
    ('PLATFORM_OWNER', 'ROLE', 'OPTIONAL'),
    ('PLATFORM_OWNER', 'INTEGRATION', 'MANDATORY'),
    ('PLATFORM_OWNER', 'SHARE', 'OPTIONAL'),
    ('DOMAIN_OWNER', 'DATABASE', 'RECOMMENDED'),
    ('DOMAIN_OWNER', 'SCHEMA', 'OPTIONAL'),
    ('DATA_PRODUCT_OWNER', 'SCHEMA', 'RECOMMENDED'),
    ('DATA_PRODUCT_OWNER', 'SHARE', 'MANDATORY'),
    ('DATA_PRODUCT_OWNER', 'STREAMLIT', 'OPTIONAL'),
    ('DATA_PRODUCT_OWNER', 'APPLICATION', 'OPTIONAL'),
    ('DATA_PRODUCT_TYPE', 'SCHEMA', 'RECOMMENDED'),
    ('DATA_PRODUCT_TYPE', 'SHARE', 'OPTIONAL'),
    ('PHI', 'SCHEMA', 'OPTIONAL'),
    ('PHI', 'TABLE', 'OPTIONAL'),
    ('PHI', 'VIEW', 'OPTIONAL'),
    ('PHI', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('PHI', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('PHI', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('PHI', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('PHI', 'COLUMN', 'RECOMMENDED'),
    ('PHI', 'STAGE', 'OPTIONAL'),
    ('PHI', 'SHARE', 'OPTIONAL'),
    ('PCI', 'SCHEMA', 'OPTIONAL'),
    ('PCI', 'TABLE', 'OPTIONAL'),
    ('PCI', 'VIEW', 'OPTIONAL'),
    ('PCI', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('PCI', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('PCI', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('PCI', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('PCI', 'COLUMN', 'RECOMMENDED'),
    ('PCI', 'STAGE', 'OPTIONAL'),
    ('PCI', 'SHARE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'DATABASE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'SCHEMA', 'OPTIONAL'),
    ('LEGAL_HOLD', 'TABLE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'VIEW', 'OPTIONAL'),
    ('LEGAL_HOLD', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('LEGAL_HOLD', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'STAGE', 'OPTIONAL'),
    ('ENCRYPTION_REQUIRED', 'TABLE', 'OPTIONAL'),
    ('ENCRYPTION_REQUIRED', 'COLUMN', 'OPTIONAL'),
    ('ENCRYPTION_REQUIRED', 'STAGE', 'RECOMMENDED'),
    ('ENCRYPTION_REQUIRED', 'PIPE', 'OPTIONAL'),
    ('ENCRYPTION_REQUIRED', 'INTEGRATION', 'OPTIONAL'),
    ('DATA_QUALITY_TIER', 'SCHEMA', 'OPTIONAL'),
    ('DATA_QUALITY_TIER', 'TABLE', 'RECOMMENDED'),
    ('DATA_QUALITY_TIER', 'VIEW', 'RECOMMENDED'),
    ('DATA_QUALITY_TIER', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('DATA_QUALITY_TIER', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('DATA_QUALITY_TIER', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('REFRESH_TYPE', 'TABLE', 'RECOMMENDED'),
    ('REFRESH_TYPE', 'VIEW', 'OPTIONAL'),
    ('REFRESH_TYPE', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('REFRESH_TYPE', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('REFRESH_TYPE', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('REFRESH_TYPE', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('REFRESH_TYPE', 'PIPE', 'RECOMMENDED'),
    ('REFRESH_TYPE', 'TASK', 'RECOMMENDED'),
    ('REFRESH_TYPE', 'STREAM', 'OPTIONAL'),
    ('PROJECT_CODE', 'DATABASE', 'OPTIONAL'),
    ('PROJECT_CODE', 'SCHEMA', 'OPTIONAL'),
    ('PROJECT_CODE', 'PIPE', 'OPTIONAL'),
    ('PROJECT_CODE', 'TASK', 'OPTIONAL'),
    ('PROJECT_CODE', 'WAREHOUSE', 'OPTIONAL'),
    ('PROJECT_CODE', 'NOTEBOOK', 'OPTIONAL'),
    ('PROJECT_CODE', 'STREAMLIT', 'OPTIONAL'),
    ('CAPABILITY', 'SCHEMA', 'OPTIONAL'),
    ('CAPABILITY', 'TABLE', 'OPTIONAL'),
    ('CAPABILITY', 'VIEW', 'OPTIONAL'),
    ('CAPABILITY', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('CAPABILITY', 'APPLICATION', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'SCHEMA', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'TABLE', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'VIEW', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'STAGE', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'PIPE', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'STREAM', 'OPTIONAL'),
    ('DATA_RESIDENCY', 'DATABASE', 'OPTIONAL'),
    ('DATA_RESIDENCY', 'SCHEMA', 'OPTIONAL'),
    ('DATA_RESIDENCY', 'TABLE', 'OPTIONAL'),
    ('DATA_RESIDENCY', 'VIEW', 'OPTIONAL'),
    ('DATA_RESIDENCY', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('DATA_RESIDENCY', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('DATA_RESIDENCY', 'STAGE', 'OPTIONAL'),
    ('DATA_RESIDENCY', 'SHARE', 'RECOMMENDED'),
    ('SENSITIVE_DATA', 'TABLE', 'OPTIONAL'),
    ('SENSITIVE_DATA', 'VIEW', 'OPTIONAL'),
    ('SENSITIVE_DATA', 'COLUMN', 'RECOMMENDED'),
    ('PROGRAM', 'DATABASE', 'OPTIONAL'),
    ('PROGRAM', 'SCHEMA', 'OPTIONAL'),
    ('PROGRAM', 'PIPE', 'OPTIONAL'),
    ('PROGRAM', 'TASK', 'OPTIONAL'),
    ('PROGRAM', 'WAREHOUSE', 'OPTIONAL'),
    ('PRODUCT_CODE', 'DATABASE', 'OPTIONAL'),
    ('PRODUCT_CODE', 'SCHEMA', 'OPTIONAL'),
    ('PRODUCT_CODE', 'WAREHOUSE', 'OPTIONAL'),
    ('PRODUCT_CODE', 'SHARE', 'OPTIONAL'),
    ('PRODUCT_OWNER', 'DATABASE', 'OPTIONAL'),
    ('PRODUCT_OWNER', 'SCHEMA', 'OPTIONAL'),
    ('PRODUCT_OWNER', 'SHARE', 'OPTIONAL'),
    ('RPO', 'DATABASE', 'OPTIONAL'),
    ('RPO', 'SCHEMA', 'OPTIONAL'),
    ('RPO', 'TABLE', 'OPTIONAL'),
    ('RPO', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('RPO', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('RTO', 'DATABASE', 'OPTIONAL'),
    ('RTO', 'SCHEMA', 'OPTIONAL'),
    ('RTO', 'TABLE', 'OPTIONAL'),
    ('RTO', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('RTO', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('SHARING_SCOPE', 'DATABASE', 'OPTIONAL'),
    ('SHARING_SCOPE', 'SCHEMA', 'OPTIONAL'),
    ('SHARING_SCOPE', 'TABLE', 'OPTIONAL'),
    ('SHARING_SCOPE', 'VIEW', 'OPTIONAL'),
    ('SHARING_SCOPE', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('SHARING_SCOPE', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('SHARING_SCOPE', 'SHARE', 'RECOMMENDED'),
    ('COST_ALLOCATION_MODEL', 'DATABASE', 'OPTIONAL'),
    ('COST_ALLOCATION_MODEL', 'SCHEMA', 'OPTIONAL'),
    ('COST_ALLOCATION_MODEL', 'WAREHOUSE', 'RECOMMENDED')
AS v(c1, c2, c3);


-- TAG_CONDITIONAL_RULE
INSERT INTO TAG_CONDITIONAL_RULE (RULE_ID, DESCRIPTION, SEVERITY, OBJECT_TYPES, PREDICATE, THEN_MANDATORY)
SELECT c1, c2, c3, PARSE_JSON(c4)::ARRAY, PARSE_JSON(c5)::OBJECT, PARSE_JSON(c6)::ARRAY
FROM VALUES
    ('CR-001', 'HIPAA-regulated objects must declare PHI status at column level.', 'HIGH', '["TABLE", "VIEW", "COLUMN"]', '{"REGULATION": ["HIPAA", "MULTI"]}', '["PHI"]'),
    ('CR-002', 'PCI-DSS-regulated objects must declare PCI status at column level.', 'CRITICAL', '["TABLE", "VIEW", "COLUMN"]', '{"REGULATION": ["PCI_DSS", "MULTI"]}', '["PCI"]'),
    ('CR-003', 'RESTRICTED and HIGHLY_RESTRICTED data must declare row-level access intent.', 'HIGH', '["TABLE", "VIEW", "MATERIALIZED_VIEW", "DYNAMIC_TABLE"]', '{"DATA_CLASSIFICATION": ["RESTRICTED", "HIGHLY_RESTRICTED"]}', '["ROW_ACCESS_REQUIRED"]'),
    ('CR-004', 'PII columns must declare masking intent.', 'CRITICAL', '["COLUMN"]', '{"PII": ["YES"]}', '["MASKING_REQUIRED"]'),
    ('CR-005', 'Objects subject to GDPR/CCPA/LGPD must declare data residency so replication and cross-region sharing can be evaluated.', 'HIGH', '["DATABASE", "SCHEMA", "SHARE"]', '{"REGULATION": ["GDPR", "CCPA", "LGPD", "MULTI"]}', '["DATA_RESIDENCY"]'),
    ('CR-006', 'CRITICAL objects must publish RPO and RTO for DR planning.', 'MEDIUM', '["DATABASE", "SCHEMA", "TABLE"]', '{"CRITICALITY": ["CRITICAL"]}', '["RPO", "RTO"]'),
    ('CR-007', 'Anything leaving the account must declare its permitted distribution.', 'CRITICAL', '["SHARE"]', '{}', '["SHARING_SCOPE", "DATA_CLASSIFICATION", "DATA_PRODUCT_OWNER"]'),
    ('CR-008', 'Project-funded workloads must carry the funding programme.', 'MEDIUM', '["WAREHOUSE", "DATABASE"]', '{"COST_ALLOCATION_MODEL": ["CHARGEBACK"]}', '["COST_CENTER"]')
AS v(c1, c2, c3, c4, c5, c6);


-- TAG_POLICY_BINDING
INSERT INTO TAG_POLICY_BINDING (TAG_NAME, TAG_VALUE, POLICY_KIND, POLICY_NAME, DATA_TYPE, ATTACH_MODE, NOTES)
SELECT c1, c2, c3, c4, c5, c6, c7
FROM VALUES
    ('DATA_CLASSIFICATION', NULL, 'MASKING', 'GOVERNANCE.POLICIES.MP_ENTERPRISE_STRING', 'STRING', 'TAG_ATTACHED', 'Bound to DATA_CLASSIFICATION only. PII/PHI/PCI deliberately carry NO policy attachment of their own - they are read inside the policy body.'),
    ('DATA_CLASSIFICATION', NULL, 'MASKING', 'GOVERNANCE.POLICIES.MP_ENTERPRISE_NUMBER', 'NUMBER', 'TAG_ATTACHED', 'Bound to DATA_CLASSIFICATION only. PII/PHI/PCI deliberately carry NO policy attachment of their own - they are read inside the policy body.'),
    ('DATA_CLASSIFICATION', NULL, 'MASKING', 'GOVERNANCE.POLICIES.MP_ENTERPRISE_DATE', 'DATE', 'TAG_ATTACHED', 'Bound to DATA_CLASSIFICATION only. PII/PHI/PCI deliberately carry NO policy attachment of their own - they are read inside the policy body.'),
    ('DATA_CLASSIFICATION', NULL, 'MASKING', 'GOVERNANCE.POLICIES.MP_ENTERPRISE_TIMESTAMP_NTZ', 'TIMESTAMP_NTZ', 'TAG_ATTACHED', 'Bound to DATA_CLASSIFICATION only. PII/PHI/PCI deliberately carry NO policy attachment of their own - they are read inside the policy body.'),
    ('DATA_CLASSIFICATION', NULL, 'MASKING', 'GOVERNANCE.POLICIES.MP_ENTERPRISE_VARIANT', 'VARIANT', 'TAG_ATTACHED', 'Bound to DATA_CLASSIFICATION only. PII/PHI/PCI deliberately carry NO policy attachment of their own - they are read inside the policy body.'),
    ('ROW_ACCESS_REQUIRED', 'YES', 'ROW_ACCESS', 'GOVERNANCE.POLICIES.RAP_BUSINESS_UNIT_SCOPE', NULL, 'RECONCILED', 'Applied by reconciliation task, not by tag attachment. The policy signature is resolved from the table''s own BUSINESS_UNIT column if present, else the table is registered in CONTROL.ROW_ACCESS_EXCEPTION for manual binding.')
AS v(c1, c2, c3, c4, c5, c6, c7);


-- REGULATION_PRECEDENCE
INSERT INTO REGULATION_PRECEDENCE (REGULATION, PRECEDENCE_ORDER, NOTES)
SELECT c1, c2::NUMBER(3,0), c3
FROM VALUES
    ('HIPAA', 1, NULL),
    ('PCI_DSS', 2, NULL),
    ('GLBA', 3, NULL),
    ('SOX', 4, NULL),
    ('GDPR', 5, NULL),
    ('LGPD', 6, NULL),
    ('PIPEDA', 7, NULL),
    ('PDPA', 8, NULL),
    ('CCPA', 9, NULL),
    ('FERPA', 10, NULL),
    ('NONE', 11, NULL)
AS v(c1, c2, c3);

COMMIT;

SELECT COUNT(*) AS tags_registered FROM TAG_CATALOG;
