-- =========================================================================
-- GENERATED FILE - DO NOT EDIT.
-- Source : config/tag_catalog.yaml
-- Rebuild: make build   (scripts/generate_sql.py)
-- CI fails if this file differs from a fresh generation.
-- =========================================================================


-- -----------------------------------------------------------------------------
-- Full refresh of the tag registry from the catalog.
-- Wrapped in a transaction so the registry is never observed half-loaded by the
-- validation task, which reads these tables on a schedule.
-- -----------------------------------------------------------------------------

USE ROLE TAG_ADMIN;
USE WAREHOUSE GOVERNANCE_WH;
USE DATABASE GOVERNANCE;
USE SCHEMA CONTROL;

BEGIN TRANSACTION;

DELETE FROM TAG_REQUIREMENT;
DELETE FROM TAG_ALLOWED_VALUE;
DELETE FROM TAG_POLICY_BINDING;
DELETE FROM TAG_CONDITIONAL_RULE;
DELETE FROM TAG_CONTRADICTION_RULE;
DELETE FROM VALUE_PRECEDENCE;
DELETE FROM TAG_CATALOG;

-- TAG_CATALOG
INSERT INTO TAG_CATALOG (TAG_NAME, CANONICAL_KEY, HIERARCHY_LEVEL, PLATFORMS, HIERARCHY_REQUIREMENT, TIER, CATEGORY, DESCRIPTION, VALUE_SOURCE, VALUE_FORMAT_REGEX, REFERENCE_SET, INHERITANCE_MODE, OVERRIDE_RULE, ORDINAL_VALUES, DRIVES, OWNER_ROLE, TAG_VERSION, STATUS, DEPRECATES, CATALOG_VERSION)
SELECT c1, c2, c3, PARSE_JSON(c4)::ARRAY, c5, c6::NUMBER(1,0), c7, c8, c9, c10, c11, c12, c13, PARSE_JSON(c14)::ARRAY, PARSE_JSON(c15)::ARRAY, c16, c17, c18, c19, c20
FROM VALUES
    ('OPERATING_COMPANY', 'operating_company', 'Operating Company', '["AWS", "SNOWFLAKE", "DENODO", "COLLIBRA"]', 'MANDATORY', 1, 'business', 'Top-level legal and financial entity for chargeback and consolidation. The consolidation boundary for every cost report and the outermost jurisdiction boundary for data residency.', 'controlled_vocabulary', '^(?:OPCO_[A-Z0-9_]{2,48}|SHARED)$', NULL, 'inherit', 'any', NULL, '["finops_chargeback", "finops_consolidation", "access_boundary", "residency_control", "discovery"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DEPARTMENT', 'department', 'Department', '["AWS", "SNOWFLAKE", "DENODO", "COLLIBRA"]', 'MANDATORY', 1, 'business', 'Business unit or cost centre within the operating company. The level at which departmental cost reports are produced and budgets are owned.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["finops_chargeback", "department_reporting", "budget_enforcement", "discovery"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DOMAIN', 'domain', 'Data Domain', '["AWS", "SNOWFLAKE", "DENODO", "COLLIBRA"]', 'MANDATORY', 1, 'business', 'Logical data domain owning the workload, mesh-style. The unit of federated governance and of data-product publication. Independent of department: one domain routinely serves several departments.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["data_mesh", "federated_governance", "discovery", "finops_showback", "row_access_policy"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('TEAM', 'team', 'Team', '["AWS", "SNOWFLAKE", "DENODO", "COLLIBRA"]', 'MANDATORY', 1, 'ownership', 'Engineering team accountable for build and run. Validated against the team registry so a disbanded team cannot keep owning production workloads.', 'reference_data', '^team-[a-z0-9][a-z0-9-]{1,48}$', 'REF_TEAM', 'inherit', 'any', NULL, '["incident_routing", "stewardship_workflow", "finops_showback", "operational_reporting"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('APPLICATION', 'application', 'Application', '["AWS", "SNOWFLAKE", "DENODO", "COLLIBRA"]', 'MANDATORY', 1, 'business', 'Discrete application or data product, aligned to the CMDB. The join key between Snowflake objects and the enterprise application portfolio, which is what makes cross-platform impact analysis possible at all.', 'reference_data', '^app-[a-z0-9][a-z0-9-]{1,48}$', 'REF_APPLICATION', 'inherit', 'any', NULL, '["cmdb_reconciliation", "impact_analysis", "finops_chargeback", "discovery", "incident_routing"]', 'ENTERPRISE_ARCHITECTURE', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('WORKLOAD_TYPE', 'workload_type', 'Role / Workload Class', '["AWS", "SNOWFLAKE", "DENODO"]', 'MANDATORY', 1, 'operational', 'Workload class, for resource-pattern rollups. Lets FinOps compare like with like across the estate - ML training spend against ML training spend, not against BI - and drives right-sizing recommendations per pattern.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["finops_rightsizing", "workload_analytics", "capacity_planning", "finops_showback"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('OWNER_USER', 'owner_user', 'Owner / User', '["AWS", "SNOWFLAKE", "DENODO", "COLLIBRA"]', 'RECOMMENDED', 1, 'ownership', 'Accountable individual by SSO email, or the named service account that owns an automated workload. Recommended rather than mandatory: an owner tag that is mandated before joiner-mover-leaver feeds are wired up fills with stale names, which is worse than an honest blank.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|service-account-[a-z0-9][a-z0-9-]{1,48})$', NULL, 'inherit', 'any', NULL, '["incident_routing", "access_approval", "attestation", "finops_accountability"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('ENVIRONMENT', 'environment', 'Environment', '["AWS", "SNOWFLAKE", "DENODO", "COLLIBRA"]', 'MANDATORY', 1, 'lifecycle', 'Lifecycle stage, required alongside the core tags. Never inherited across a clone into a different environment - the clone-remediation job rewrites it.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'none', NULL, '["policy_selection", "promotion_gate", "finops_chargeback", "masking_strictness", "nonprod_waste_analysis"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'data_classification_enterprise', 'Data Classification', '["AWS", "SNOWFLAKE", "DENODO", "COLLIBRA"]', 'MANDATORY', 1, 'classification', 'Core enterprise confidentiality classification. The only tag carrying masking policy attachments, so it is the anchor of the whole protection model. Most restrictive value in the lineage wins.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NONE", "PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"]', '["dynamic_masking", "sharing_control", "export_control", "compliance_reporting", "discovery"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DATA_CLASSIFICATION_REGULATORY', 'data_classification_regulatory', 'Data Classification', '["AWS", "SNOWFLAKE", "DENODO", "COLLIBRA"]', 'MANDATORY', 1, 'privacy', 'Regulatory-driven data classification. Holds the GOVERNING category - the one whose technical controls are most prescriptive - resolved by documented precedence. Where several categories apply, the full set is recorded in CONTROL.REGULATORY_SCOPE, because a Snowflake tag holds only one value.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NONE", "PII", "SPII", "PHI", "PCI"]', '["dynamic_masking", "privacy_reporting", "dsar_fulfilment", "audit_evidence", "auto_classification", "pci_scoping"]', 'PRIVACY_OFFICE', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DATA_PRODUCT', 'data_product', 'Data Product', '["SNOWFLAKE", "DENODO", "COLLIBRA"]', NULL, 2, 'business', 'Named, versioned, independently consumable data product. Maps 1:1 to a schema, which is the publication boundary. Distinct from `application`: one application can publish several data products.', 'reference_data', '^dp-[a-z0-9][a-z0-9-]{2,48}$', 'REF_DATA_PRODUCT', 'inherit', 'none', NULL, '["data_mesh", "discovery", "lineage", "sla_management", "consumer_contract"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DATA_OWNER', 'data_owner', 'Ownership', '["SNOWFLAKE", "DENODO", "COLLIBRA"]', NULL, 2, 'ownership', 'Accountable business owner (RACI ''A'') for the DATA, as distinct from owner_user who is accountable for the RESOURCE. Approves access, classification and retention decisions.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|GRP-[A-Z0-9-]{3,48})$', NULL, 'inherit', 'any', NULL, '["access_approval", "attestation", "remediation_routing", "audit_evidence"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DATA_STEWARD', 'data_steward', 'Ownership', '["SNOWFLAKE", "COLLIBRA"]', NULL, 2, 'ownership', 'Responsible steward (RACI ''R'') executing day-to-day governance: tagging, classification review, quality remediation, metadata curation.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|GRP-[A-Z0-9-]{3,48})$', NULL, 'inherit', 'any', NULL, '["stewardship_workflow", "attestation", "remediation_routing"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('SUPPORT_GROUP', 'support_group', 'Ownership', '["AWS", "SNOWFLAKE", "DENODO"]', NULL, 2, 'ownership', 'ITSM queue that owns break/fix. Complements `team`, which names the accountable engineers; support_group names where the ticket actually lands out of hours.', 'reference_data', '^GRP-[A-Z0-9-]{3,48}$', 'REF_SUPPORT_GROUP', 'inherit', 'any', NULL, '["incident_routing", "sla_management", "operational_reporting"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('COST_CENTER', 'cost_center', 'Financial', '["AWS", "SNOWFLAKE"]', NULL, 2, 'financial', 'GL cost centre code. `department` is the human-facing allocation level; cost_center is the posting key a journal entry actually needs. Required wherever cost_allocation_model is CHARGEBACK.', 'reference_data', '^CC-[0-9]{4,8}$', 'REF_COST_CENTER', 'inherit', 'any', NULL, '["finops_chargeback", "budget_enforcement", "gl_posting"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('CRITICALITY', 'criticality', 'Lifecycle', '["AWS", "SNOWFLAKE", "DENODO"]', NULL, 2, 'lifecycle', 'Business impact if the object is unavailable or incorrect. Drives DR scope, monitoring depth, change-control rigour and incident severity.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["LOW", "MEDIUM", "HIGH", "CRITICAL"]', '["dr_scope", "monitoring_depth", "change_control", "incident_severity"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DATA_LIFECYCLE', 'data_lifecycle', 'Lifecycle', '["SNOWFLAKE", "DENODO", "COLLIBRA"]', NULL, 2, 'lifecycle', 'Lifecycle state of the object itself. Drives deprecation comms, consumer warnings and the automated archive/purge pipeline. Deprecated data nobody deleted is consistently one of the largest recoverable cost lines.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["retirement_automation", "consumer_notification", "cost_avoidance", "discovery"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('RETENTION_CLASS', 'retention_class', 'Compliance', '["AWS", "SNOWFLAKE", "COLLIBRA"]', NULL, 2, 'compliance', 'Records-management retention class from the enterprise retention schedule. Drives the automated archive and purge pipeline. legal_hold always supersedes it.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["retention_automation", "purge_pipeline", "compliance_reporting", "storage_cost_control"]', 'RECORDS_MANAGEMENT', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('LEGAL_HOLD', 'legal_hold', 'Compliance', '["SNOWFLAKE", "COLLIBRA"]', NULL, 2, 'compliance', 'Litigation hold. When YES, all retention-driven archive and purge automation is suppressed regardless of retention_class. Set only by Legal.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["purge_suppression", "ediscovery", "audit_evidence"]', 'LEGAL', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('REGULATION', 'regulation', 'Compliance', '["SNOWFLAKE", "COLLIBRA"]', NULL, 2, 'compliance', 'The governing regulatory REGIME, as distinct from data_classification_regulatory which states what the DATA IS. A financial ledger with no personal data at all is still in SOX scope; the two tags answer different questions and are both needed for evidence.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["compliance_reporting", "audit_evidence", "policy_selection", "residency_control"]', 'COMPLIANCE_OFFICE', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('SLA_TIER', 'sla_tier', 'Operational', '["SNOWFLAKE", "DENODO"]', NULL, 2, 'operational', 'Freshness and availability commitment published to consumers. Drives monitoring thresholds, alert routing and DR tiering.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', '["BEST_EFFORT", "BRONZE_24H", "SILVER_4H", "GOLD_1H", "PLATINUM_15M"]', '["sla_management", "monitoring_depth", "alert_routing", "dr_scope"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('MASKING_REQUIRED', 'masking_required', 'Security', '["SNOWFLAKE"]', NULL, 2, 'security', 'Declares that the column must carry a masking policy. This is DECLARED INTENT; the tag-based policy attachment is ENFORCEMENT. The drift detector reconciles the two, and divergence is the finding that matters most.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["dynamic_masking", "control_attestation", "drift_detection"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('ROW_ACCESS_REQUIRED', 'row_access_required', 'Security', '["SNOWFLAKE"]', NULL, 2, 'security', 'Declares that the table or view must carry a row access policy. Snowflake does NOT support attaching row access policies to tags, so enforcement runs through the SP_APPLY_ROW_ACCESS_POLICIES reconciliation task.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["row_access_policy", "control_attestation", "drift_detection"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DATA_RESIDENCY', 'data_residency', 'Compliance', '["AWS", "SNOWFLAKE", "DENODO"]', NULL, 2, 'compliance', 'Region in which the data must remain. Drives replication scope and cross-region share eligibility.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["residency_control", "replication_control", "sharing_control", "compliance_reporting"]', 'COMPLIANCE_OFFICE', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DATA_QUALITY_TIER', 'data_quality_tier', 'Data Quality', '["SNOWFLAKE", "COLLIBRA"]', NULL, 2, 'data_quality', 'Certified quality level. Set only by the data-quality pipeline once data metric function results are evaluated; never inherited, because a table in a GOLD schema is not GOLD until its own measurements say so.', 'controlled_vocabulary', NULL, NULL, 'explicit_only', 'any', '["BRONZE", "SILVER", "GOLD", "PLATINUM"]', '["quality_reporting", "consumer_contract", "discovery", "certification"]', 'EDGO', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('SUB_DOMAIN', 'sub_domain', 'Data Domain', '["SNOWFLAKE", "COLLIBRA"]', NULL, 3, 'business', 'Second-level decomposition of domain, for large domains only.', 'reference_data', '^[A-Z0-9][A-Z0-9_]{1,62}$', 'REF_SUB_DOMAIN', 'inherit', 'any', NULL, '["discovery", "federated_governance", "finops_showback"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('SOURCE_SYSTEM', 'source_system', 'Application', '["SNOWFLAKE", "DENODO", "COLLIBRA"]', NULL, 3, 'business', 'System of record the data originates from. Roots lineage at the edge.', 'reference_data', '^app-[a-z0-9][a-z0-9-]{1,48}$', 'REF_APPLICATION', 'inherit', 'any', NULL, '["lineage", "impact_analysis", "discovery"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('APPLICATION_OWNER', 'application_owner', 'Ownership', '["SNOWFLAKE", "COLLIBRA"]', NULL, 3, 'ownership', 'Accountable owner of the application referenced by the object.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|service-account-[a-z0-9][a-z0-9-]{1,48})$', NULL, 'inherit', 'any', NULL, '["impact_analysis", "incident_routing", "attestation"]', 'ENTERPRISE_ARCHITECTURE', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('PLATFORM_OWNER', 'platform_owner', 'Ownership', '["AWS", "SNOWFLAKE"]', NULL, 3, 'ownership', 'Platform engineering team accountable for the infrastructure object.', 'reference_data', '^GRP-[A-Z0-9-]{3,48}$', 'REF_SUPPORT_GROUP', 'inherit', 'any', NULL, '["incident_routing", "platform_attestation", "finops_chargeback"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DOMAIN_OWNER', 'domain_owner', 'Data Domain', '["SNOWFLAKE", "COLLIBRA"]', NULL, 3, 'data_mesh', 'Accountable owner of the mesh domain. Normally set once, on the domain''s database.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|GRP-[A-Z0-9-]{3,48})$', NULL, 'inherit', 'any', NULL, '["data_mesh", "federated_governance", "access_approval"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DATA_PRODUCT_OWNER', 'data_product_owner', 'Data Product', '["SNOWFLAKE", "COLLIBRA"]', NULL, 3, 'data_mesh', 'Product owner accountable for the data product''s roadmap, SLA and consumer contract. Distinct from data_owner, who is accountable for the data itself.', 'free_text', '^(?:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|GRP-[A-Z0-9-]{3,48})$', NULL, 'inherit', 'any', NULL, '["data_mesh", "sla_management", "consumer_contract", "access_approval"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('DATA_PRODUCT_TYPE', 'data_product_type', 'Data Product', '["SNOWFLAKE", "COLLIBRA"]', NULL, 3, 'data_mesh', 'Mesh archetype; sets default quality and SLA expectations.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["data_mesh", "discovery", "quality_expectation"]', 'DOMAIN_COUNCIL', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('CAPABILITY', 'capability', 'Business Capability', '["COLLIBRA"]', NULL, 3, 'business', 'Business capability from the enterprise capability model (L2).', 'reference_data', '^[A-Z0-9][A-Z0-9_]{1,62}$', 'REF_CAPABILITY', 'inherit', 'any', NULL, '["discovery", "portfolio_analysis"]', 'ENTERPRISE_ARCHITECTURE', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('PROJECT_CODE', 'project_code', 'Financial', '["AWS", "SNOWFLAKE"]', NULL, 3, 'financial', 'Capital or programme project funding the workload.', 'reference_data', '^(PRJ|PRG)-[A-Z0-9]{2,4}-[0-9]{3,6}$', 'REF_PROJECT', 'inherit', 'any', NULL, '["finops_chargeback", "project_reporting", "capitalisation"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('COST_ALLOCATION_MODEL', 'cost_allocation_model', 'Financial', '["AWS", "SNOWFLAKE"]', NULL, 3, 'financial', 'How this object''s consumption is settled with the business. SHOWBACK reports only; CHARGEBACK posts a journal entry to the ERP.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', NULL, '["finops_chargeback", "department_reporting"]', 'FINANCE_FINOPS', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('ENCRYPTION_REQUIRED', 'encryption_required', 'Security', '["AWS", "SNOWFLAKE"]', NULL, 3, 'security', 'Declares that application-layer or client-side encryption is required in addition to transparent encryption at rest. Mainly external stages and columns holding secrets or key material.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'more_restrictive_only', '["NO", "YES"]', '["encryption_control", "audit_evidence", "drift_detection"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('SHARING_SCOPE', 'sharing_scope', 'Security', '["SNOWFLAKE", "DENODO"]', NULL, 3, 'security', 'Maximum permitted distribution. Checked before any listing, share or reader-account grant is created.', 'controlled_vocabulary', NULL, NULL, 'inherit', 'any', '["PROHIBITED", "INTERNAL_ONLY", "AFFILIATE", "PARTNER", "PUBLIC_MARKETPLACE"]', '["sharing_control", "export_control", "compliance_reporting"]', 'CISO_DATA_SECURITY', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('REFRESH_TYPE', 'refresh_type', 'Operational', '["SNOWFLAKE", "DENODO"]', NULL, 3, 'operational', 'How the object''s data is refreshed. Drives freshness monitoring logic.', 'controlled_vocabulary', NULL, NULL, 'explicit_only', 'any', NULL, '["freshness_monitoring", "sla_management", "lineage"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('RPO', 'rpo', 'Operational', '["AWS", "SNOWFLAKE"]', NULL, 3, 'operational', 'Recovery Point Objective as an ISO-8601 duration (e.g. PT15M, P1D).', 'free_text', '^PT(?:[0-9]{1,3}H)?(?:[0-9]{1,3}M)?$|^P[0-9]{1,3}D$', NULL, 'inherit', 'any', NULL, '["dr_scope", "replication_control", "sla_management"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '2.0.0'),
    ('RTO', 'rto', 'Operational', '["AWS", "SNOWFLAKE"]', NULL, 3, 'operational', 'Recovery Time Objective as an ISO-8601 duration (e.g. PT4H, P1D).', 'free_text', '^PT(?:[0-9]{1,3}H)?(?:[0-9]{1,3}M)?$|^P[0-9]{1,3}D$', NULL, 'inherit', 'any', NULL, '["dr_scope", "sla_management"]', 'PLATFORM_ENGINEERING', '1.0.0', 'ACTIVE', NULL, '2.0.0')
AS v(c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20);


-- TAG_ALLOWED_VALUE
INSERT INTO TAG_ALLOWED_VALUE (TAG_NAME, TAG_VALUE, ORDINAL_POSITION)
SELECT c1, c2, c3::NUMBER(5,0)
FROM VALUES
    ('OPERATING_COMPANY', 'OPCO_AEP_OHIO', NULL),
    ('OPERATING_COMPANY', 'OPCO_AEP_TEXAS', NULL),
    ('OPERATING_COMPANY', 'OPCO_APPALACHIAN', NULL),
    ('OPERATING_COMPANY', 'OPCO_AEP_INDIANA_MICHIGAN', NULL),
    ('OPERATING_COMPANY', 'OPCO_KENTUCKY_POWER', NULL),
    ('OPERATING_COMPANY', 'OPCO_PSC_OKLAHOMA', NULL),
    ('OPERATING_COMPANY', 'OPCO_SEPC', NULL),
    ('OPERATING_COMPANY', 'SHARED', NULL),
    ('DEPARTMENT', 'FINANCE', NULL),
    ('DEPARTMENT', 'HR', NULL),
    ('DEPARTMENT', 'MARKETING', NULL),
    ('DEPARTMENT', 'DISTRIBUTION', NULL),
    ('DEPARTMENT', 'GENERATION', NULL),
    ('DEPARTMENT', 'COMOPS', NULL),
    ('DEPARTMENT', 'GIS', NULL),
    ('DEPARTMENT', 'CORPORATE', NULL),
    ('DEPARTMENT', 'CUSTOMER', NULL),
    ('DEPARTMENT', 'SHARED_SERVICES', NULL),
    ('DOMAIN', 'CUSTOMER', NULL),
    ('DOMAIN', 'LOCATION', NULL),
    ('DOMAIN', 'METER', NULL),
    ('DOMAIN', 'FINANCE', NULL),
    ('DOMAIN', 'SUPPLY_CHAIN', NULL),
    ('DOMAIN', 'MARKETING', NULL),
    ('DOMAIN', 'RISK', NULL),
    ('DOMAIN', 'TELEMETRY', NULL),
    ('WORKLOAD_TYPE', 'INGEST', NULL),
    ('WORKLOAD_TYPE', 'TRANSFORM', NULL),
    ('WORKLOAD_TYPE', 'ANALYTICS', NULL),
    ('WORKLOAD_TYPE', 'ML_TRAIN', NULL),
    ('WORKLOAD_TYPE', 'ML_SERVE', NULL),
    ('WORKLOAD_TYPE', 'BI', NULL),
    ('WORKLOAD_TYPE', 'GOVERNANCE', NULL),
    ('WORKLOAD_TYPE', 'PLATFORM_OPS', NULL),
    ('ENVIRONMENT', 'PRD', NULL),
    ('ENVIRONMENT', 'UAT', NULL),
    ('ENVIRONMENT', 'TST', NULL),
    ('ENVIRONMENT', 'DEV', NULL),
    ('ENVIRONMENT', 'TRAINING', NULL),
    ('ENVIRONMENT', 'BACKUP', NULL),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'NONE', 1),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'PUBLIC', 2),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'INTERNAL', 3),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'CONFIDENTIAL', 4),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'RESTRICTED', 5),
    ('DATA_CLASSIFICATION_REGULATORY', 'NONE', 1),
    ('DATA_CLASSIFICATION_REGULATORY', 'PII', 2),
    ('DATA_CLASSIFICATION_REGULATORY', 'SPII', 3),
    ('DATA_CLASSIFICATION_REGULATORY', 'PHI', 4),
    ('DATA_CLASSIFICATION_REGULATORY', 'PCI', 5),
    ('CRITICALITY', 'LOW', 1),
    ('CRITICALITY', 'MEDIUM', 2),
    ('CRITICALITY', 'HIGH', 3),
    ('CRITICALITY', 'CRITICAL', 4),
    ('DATA_LIFECYCLE', 'ACTIVE', NULL),
    ('DATA_LIFECYCLE', 'DEPRECATED', NULL),
    ('DATA_LIFECYCLE', 'ARCHIVED', NULL),
    ('DATA_LIFECYCLE', 'PENDING_PURGE', NULL),
    ('RETENTION_CLASS', 'TRANSIENT_30D', NULL),
    ('RETENTION_CLASS', 'SHORT_1Y', NULL),
    ('RETENTION_CLASS', 'STANDARD_3Y', NULL),
    ('RETENTION_CLASS', 'EXTENDED_7Y', NULL),
    ('RETENTION_CLASS', 'REGULATORY_10Y', NULL),
    ('RETENTION_CLASS', 'PERMANENT', NULL),
    ('RETENTION_CLASS', 'INDEFINITE_REVIEW', NULL),
    ('LEGAL_HOLD', 'YES', 2),
    ('LEGAL_HOLD', 'NO', 1),
    ('REGULATION', 'NONE', NULL),
    ('REGULATION', 'SOX', NULL),
    ('REGULATION', 'GDPR', NULL),
    ('REGULATION', 'CCPA', NULL),
    ('REGULATION', 'HIPAA', NULL),
    ('REGULATION', 'PCI_DSS', NULL),
    ('REGULATION', 'GLBA', NULL),
    ('REGULATION', 'FERPA', NULL),
    ('REGULATION', 'NERC_CIP', NULL),
    ('REGULATION', 'MULTI', NULL),
    ('SLA_TIER', 'PLATINUM_15M', 5),
    ('SLA_TIER', 'GOLD_1H', 4),
    ('SLA_TIER', 'SILVER_4H', 3),
    ('SLA_TIER', 'BRONZE_24H', 2),
    ('SLA_TIER', 'BEST_EFFORT', 1),
    ('MASKING_REQUIRED', 'YES', 2),
    ('MASKING_REQUIRED', 'NO', 1),
    ('ROW_ACCESS_REQUIRED', 'YES', 2),
    ('ROW_ACCESS_REQUIRED', 'NO', 1),
    ('DATA_RESIDENCY', 'US', NULL),
    ('DATA_RESIDENCY', 'US_EAST', NULL),
    ('DATA_RESIDENCY', 'US_WEST', NULL),
    ('DATA_RESIDENCY', 'EU', NULL),
    ('DATA_RESIDENCY', 'UK', NULL),
    ('DATA_RESIDENCY', 'CANADA', NULL),
    ('DATA_RESIDENCY', 'APAC', NULL),
    ('DATA_RESIDENCY', 'GLOBAL', NULL),
    ('DATA_QUALITY_TIER', 'BRONZE', 1),
    ('DATA_QUALITY_TIER', 'SILVER', 2),
    ('DATA_QUALITY_TIER', 'GOLD', 3),
    ('DATA_QUALITY_TIER', 'PLATINUM', 4),
    ('DATA_PRODUCT_TYPE', 'SOURCE_ALIGNED', NULL),
    ('DATA_PRODUCT_TYPE', 'AGGREGATE', NULL),
    ('DATA_PRODUCT_TYPE', 'CONSUMER_ALIGNED', NULL),
    ('DATA_PRODUCT_TYPE', 'SHARED', NULL),
    ('DATA_PRODUCT_TYPE', 'PLATFORM', NULL),
    ('COST_ALLOCATION_MODEL', 'SHOWBACK', NULL),
    ('COST_ALLOCATION_MODEL', 'CHARGEBACK', NULL),
    ('COST_ALLOCATION_MODEL', 'SHARED_SERVICE', NULL),
    ('COST_ALLOCATION_MODEL', 'ABSORBED_PLATFORM', NULL),
    ('ENCRYPTION_REQUIRED', 'YES', 2),
    ('ENCRYPTION_REQUIRED', 'NO', 1),
    ('SHARING_SCOPE', 'PROHIBITED', 1),
    ('SHARING_SCOPE', 'INTERNAL_ONLY', 2),
    ('SHARING_SCOPE', 'AFFILIATE', 3),
    ('SHARING_SCOPE', 'PARTNER', 4),
    ('SHARING_SCOPE', 'PUBLIC_MARKETPLACE', 5),
    ('REFRESH_TYPE', 'STREAMING', NULL),
    ('REFRESH_TYPE', 'MICRO_BATCH', NULL),
    ('REFRESH_TYPE', 'BATCH_HOURLY', NULL),
    ('REFRESH_TYPE', 'BATCH_DAILY', NULL),
    ('REFRESH_TYPE', 'BATCH_WEEKLY', NULL),
    ('REFRESH_TYPE', 'BATCH_MONTHLY', NULL),
    ('REFRESH_TYPE', 'ON_DEMAND', NULL),
    ('REFRESH_TYPE', 'STATIC', NULL)
AS v(c1, c2, c3);


-- TAG_REQUIREMENT
INSERT INTO TAG_REQUIREMENT (TAG_NAME, OBJECT_TYPE, REQUIREMENT_LEVEL)
SELECT c1, c2, c3
FROM VALUES
    ('OPERATING_COMPANY', 'ACCOUNT', 'INHERITED'),
    ('OPERATING_COMPANY', 'DATABASE', 'MANDATORY'),
    ('OPERATING_COMPANY', 'SCHEMA', 'INHERITED'),
    ('OPERATING_COMPANY', 'TABLE', 'INHERITED'),
    ('OPERATING_COMPANY', 'VIEW', 'INHERITED'),
    ('OPERATING_COMPANY', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('OPERATING_COMPANY', 'DYNAMIC_TABLE', 'INHERITED'),
    ('OPERATING_COMPANY', 'ICEBERG_TABLE', 'INHERITED'),
    ('OPERATING_COMPANY', 'STAGE', 'INHERITED'),
    ('OPERATING_COMPANY', 'PIPE', 'INHERITED'),
    ('OPERATING_COMPANY', 'TASK', 'INHERITED'),
    ('OPERATING_COMPANY', 'STREAM', 'INHERITED'),
    ('OPERATING_COMPANY', 'WAREHOUSE', 'MANDATORY'),
    ('OPERATING_COMPANY', 'ROLE', 'RECOMMENDED'),
    ('OPERATING_COMPANY', 'USER', 'INHERITED'),
    ('OPERATING_COMPANY', 'SHARE', 'INHERITED'),
    ('OPERATING_COMPANY', 'NOTEBOOK', 'INHERITED'),
    ('OPERATING_COMPANY', 'STREAMLIT', 'INHERITED'),
    ('OPERATING_COMPANY', 'APPLICATION', 'INHERITED'),
    ('DEPARTMENT', 'DATABASE', 'MANDATORY'),
    ('DEPARTMENT', 'SCHEMA', 'INHERITED'),
    ('DEPARTMENT', 'TABLE', 'INHERITED'),
    ('DEPARTMENT', 'VIEW', 'INHERITED'),
    ('DEPARTMENT', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DEPARTMENT', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DEPARTMENT', 'ICEBERG_TABLE', 'INHERITED'),
    ('DEPARTMENT', 'STAGE', 'INHERITED'),
    ('DEPARTMENT', 'PIPE', 'INHERITED'),
    ('DEPARTMENT', 'TASK', 'INHERITED'),
    ('DEPARTMENT', 'STREAM', 'INHERITED'),
    ('DEPARTMENT', 'WAREHOUSE', 'MANDATORY'),
    ('DEPARTMENT', 'ROLE', 'INHERITED'),
    ('DEPARTMENT', 'NOTEBOOK', 'INHERITED'),
    ('DEPARTMENT', 'STREAMLIT', 'INHERITED'),
    ('DEPARTMENT', 'APPLICATION', 'INHERITED'),
    ('DOMAIN', 'DATABASE', 'MANDATORY'),
    ('DOMAIN', 'SCHEMA', 'MANDATORY'),
    ('DOMAIN', 'TABLE', 'INHERITED'),
    ('DOMAIN', 'VIEW', 'INHERITED'),
    ('DOMAIN', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DOMAIN', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DOMAIN', 'ICEBERG_TABLE', 'INHERITED'),
    ('DOMAIN', 'STAGE', 'INHERITED'),
    ('DOMAIN', 'PIPE', 'INHERITED'),
    ('DOMAIN', 'TASK', 'INHERITED'),
    ('DOMAIN', 'STREAM', 'INHERITED'),
    ('DOMAIN', 'WAREHOUSE', 'INHERITED'),
    ('DOMAIN', 'SHARE', 'INHERITED'),
    ('DOMAIN', 'NOTEBOOK', 'INHERITED'),
    ('DOMAIN', 'STREAMLIT', 'INHERITED'),
    ('DOMAIN', 'APPLICATION', 'INHERITED'),
    ('TEAM', 'DATABASE', 'MANDATORY'),
    ('TEAM', 'SCHEMA', 'MANDATORY'),
    ('TEAM', 'TABLE', 'INHERITED'),
    ('TEAM', 'VIEW', 'INHERITED'),
    ('TEAM', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('TEAM', 'DYNAMIC_TABLE', 'INHERITED'),
    ('TEAM', 'ICEBERG_TABLE', 'INHERITED'),
    ('TEAM', 'STAGE', 'INHERITED'),
    ('TEAM', 'PIPE', 'MANDATORY'),
    ('TEAM', 'TASK', 'MANDATORY'),
    ('TEAM', 'STREAM', 'INHERITED'),
    ('TEAM', 'FUNCTION', 'INHERITED'),
    ('TEAM', 'PROCEDURE', 'INHERITED'),
    ('TEAM', 'WAREHOUSE', 'MANDATORY'),
    ('TEAM', 'NOTEBOOK', 'INHERITED'),
    ('TEAM', 'STREAMLIT', 'INHERITED'),
    ('TEAM', 'APPLICATION', 'INHERITED'),
    ('APPLICATION', 'DATABASE', 'INHERITED'),
    ('APPLICATION', 'SCHEMA', 'MANDATORY'),
    ('APPLICATION', 'TABLE', 'INHERITED'),
    ('APPLICATION', 'VIEW', 'INHERITED'),
    ('APPLICATION', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('APPLICATION', 'DYNAMIC_TABLE', 'INHERITED'),
    ('APPLICATION', 'ICEBERG_TABLE', 'INHERITED'),
    ('APPLICATION', 'STAGE', 'INHERITED'),
    ('APPLICATION', 'PIPE', 'MANDATORY'),
    ('APPLICATION', 'TASK', 'MANDATORY'),
    ('APPLICATION', 'STREAM', 'INHERITED'),
    ('APPLICATION', 'WAREHOUSE', 'MANDATORY'),
    ('APPLICATION', 'INTEGRATION', 'INHERITED'),
    ('APPLICATION', 'SHARE', 'INHERITED'),
    ('APPLICATION', 'NOTEBOOK', 'INHERITED'),
    ('APPLICATION', 'STREAMLIT', 'INHERITED'),
    ('APPLICATION', 'APPLICATION', 'INHERITED'),
    ('WORKLOAD_TYPE', 'SCHEMA', 'RECOMMENDED'),
    ('WORKLOAD_TYPE', 'TABLE', 'INHERITED'),
    ('WORKLOAD_TYPE', 'VIEW', 'INHERITED'),
    ('WORKLOAD_TYPE', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('WORKLOAD_TYPE', 'DYNAMIC_TABLE', 'INHERITED'),
    ('WORKLOAD_TYPE', 'STAGE', 'INHERITED'),
    ('WORKLOAD_TYPE', 'PIPE', 'MANDATORY'),
    ('WORKLOAD_TYPE', 'TASK', 'MANDATORY'),
    ('WORKLOAD_TYPE', 'STREAM', 'INHERITED'),
    ('WORKLOAD_TYPE', 'FUNCTION', 'INHERITED'),
    ('WORKLOAD_TYPE', 'PROCEDURE', 'INHERITED'),
    ('WORKLOAD_TYPE', 'WAREHOUSE', 'MANDATORY'),
    ('WORKLOAD_TYPE', 'NOTEBOOK', 'INHERITED'),
    ('WORKLOAD_TYPE', 'STREAMLIT', 'INHERITED'),
    ('OWNER_USER', 'ACCOUNT', 'OPTIONAL'),
    ('OWNER_USER', 'DATABASE', 'RECOMMENDED'),
    ('OWNER_USER', 'SCHEMA', 'RECOMMENDED'),
    ('OWNER_USER', 'TABLE', 'OPTIONAL'),
    ('OWNER_USER', 'VIEW', 'OPTIONAL'),
    ('OWNER_USER', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('OWNER_USER', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('OWNER_USER', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('OWNER_USER', 'STAGE', 'OPTIONAL'),
    ('OWNER_USER', 'PIPE', 'OPTIONAL'),
    ('OWNER_USER', 'TASK', 'OPTIONAL'),
    ('OWNER_USER', 'STREAM', 'OPTIONAL'),
    ('OWNER_USER', 'WAREHOUSE', 'RECOMMENDED'),
    ('OWNER_USER', 'ROLE', 'OPTIONAL'),
    ('OWNER_USER', 'USER', 'OPTIONAL'),
    ('OWNER_USER', 'INTEGRATION', 'OPTIONAL'),
    ('OWNER_USER', 'SHARE', 'OPTIONAL'),
    ('OWNER_USER', 'NOTEBOOK', 'OPTIONAL'),
    ('OWNER_USER', 'STREAMLIT', 'OPTIONAL'),
    ('OWNER_USER', 'APPLICATION', 'OPTIONAL'),
    ('ENVIRONMENT', 'ACCOUNT', 'INHERITED'),
    ('ENVIRONMENT', 'DATABASE', 'MANDATORY'),
    ('ENVIRONMENT', 'SCHEMA', 'INHERITED'),
    ('ENVIRONMENT', 'STAGE', 'INHERITED'),
    ('ENVIRONMENT', 'PIPE', 'INHERITED'),
    ('ENVIRONMENT', 'TASK', 'INHERITED'),
    ('ENVIRONMENT', 'STREAM', 'INHERITED'),
    ('ENVIRONMENT', 'WAREHOUSE', 'MANDATORY'),
    ('ENVIRONMENT', 'ROLE', 'INHERITED'),
    ('ENVIRONMENT', 'INTEGRATION', 'INHERITED'),
    ('ENVIRONMENT', 'NOTEBOOK', 'INHERITED'),
    ('ENVIRONMENT', 'STREAMLIT', 'INHERITED'),
    ('ENVIRONMENT', 'APPLICATION', 'INHERITED'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'ACCOUNT', 'INHERITED'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'DATABASE', 'MANDATORY'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'SCHEMA', 'MANDATORY'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'TABLE', 'MANDATORY'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'VIEW', 'MANDATORY'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'EXTERNAL_TABLE', 'INHERITED'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'COLUMN', 'RECOMMENDED'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'STAGE', 'MANDATORY'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'SHARE', 'MANDATORY'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'NOTEBOOK', 'INHERITED'),
    ('DATA_CLASSIFICATION_ENTERPRISE', 'STREAMLIT', 'INHERITED'),
    ('DATA_CLASSIFICATION_REGULATORY', 'DATABASE', 'INHERITED'),
    ('DATA_CLASSIFICATION_REGULATORY', 'SCHEMA', 'MANDATORY'),
    ('DATA_CLASSIFICATION_REGULATORY', 'TABLE', 'MANDATORY'),
    ('DATA_CLASSIFICATION_REGULATORY', 'VIEW', 'MANDATORY'),
    ('DATA_CLASSIFICATION_REGULATORY', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_CLASSIFICATION_REGULATORY', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_CLASSIFICATION_REGULATORY', 'EXTERNAL_TABLE', 'INHERITED'),
    ('DATA_CLASSIFICATION_REGULATORY', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_CLASSIFICATION_REGULATORY', 'COLUMN', 'MANDATORY'),
    ('DATA_CLASSIFICATION_REGULATORY', 'STAGE', 'MANDATORY'),
    ('DATA_CLASSIFICATION_REGULATORY', 'SHARE', 'MANDATORY'),
    ('DATA_PRODUCT', 'SCHEMA', 'RECOMMENDED'),
    ('DATA_PRODUCT', 'TABLE', 'INHERITED'),
    ('DATA_PRODUCT', 'VIEW', 'INHERITED'),
    ('DATA_PRODUCT', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_PRODUCT', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_PRODUCT', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_PRODUCT', 'STAGE', 'INHERITED'),
    ('DATA_PRODUCT', 'PIPE', 'INHERITED'),
    ('DATA_PRODUCT', 'TASK', 'INHERITED'),
    ('DATA_PRODUCT', 'STREAM', 'INHERITED'),
    ('DATA_PRODUCT', 'SHARE', 'MANDATORY'),
    ('DATA_PRODUCT', 'NOTEBOOK', 'INHERITED'),
    ('DATA_PRODUCT', 'STREAMLIT', 'INHERITED'),
    ('DATA_OWNER', 'DATABASE', 'INHERITED'),
    ('DATA_OWNER', 'SCHEMA', 'RECOMMENDED'),
    ('DATA_OWNER', 'TABLE', 'INHERITED'),
    ('DATA_OWNER', 'VIEW', 'INHERITED'),
    ('DATA_OWNER', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_OWNER', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_OWNER', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_OWNER', 'STAGE', 'INHERITED'),
    ('DATA_OWNER', 'SHARE', 'MANDATORY'),
    ('DATA_OWNER', 'APPLICATION', 'INHERITED'),
    ('DATA_STEWARD', 'DATABASE', 'INHERITED'),
    ('DATA_STEWARD', 'SCHEMA', 'RECOMMENDED'),
    ('DATA_STEWARD', 'TABLE', 'INHERITED'),
    ('DATA_STEWARD', 'VIEW', 'INHERITED'),
    ('DATA_STEWARD', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_STEWARD', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_STEWARD', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_STEWARD', 'STAGE', 'INHERITED'),
    ('SUPPORT_GROUP', 'DATABASE', 'INHERITED'),
    ('SUPPORT_GROUP', 'SCHEMA', 'INHERITED'),
    ('SUPPORT_GROUP', 'TABLE', 'INHERITED'),
    ('SUPPORT_GROUP', 'VIEW', 'INHERITED'),
    ('SUPPORT_GROUP', 'DYNAMIC_TABLE', 'INHERITED'),
    ('SUPPORT_GROUP', 'STAGE', 'INHERITED'),
    ('SUPPORT_GROUP', 'PIPE', 'INHERITED'),
    ('SUPPORT_GROUP', 'TASK', 'INHERITED'),
    ('SUPPORT_GROUP', 'STREAM', 'INHERITED'),
    ('SUPPORT_GROUP', 'WAREHOUSE', 'INHERITED'),
    ('SUPPORT_GROUP', 'INTEGRATION', 'INHERITED'),
    ('SUPPORT_GROUP', 'APPLICATION', 'INHERITED'),
    ('COST_CENTER', 'ACCOUNT', 'INHERITED'),
    ('COST_CENTER', 'DATABASE', 'RECOMMENDED'),
    ('COST_CENTER', 'SCHEMA', 'INHERITED'),
    ('COST_CENTER', 'PIPE', 'INHERITED'),
    ('COST_CENTER', 'TASK', 'INHERITED'),
    ('COST_CENTER', 'WAREHOUSE', 'RECOMMENDED'),
    ('COST_CENTER', 'ROLE', 'INHERITED'),
    ('COST_CENTER', 'USER', 'INHERITED'),
    ('COST_CENTER', 'NOTEBOOK', 'INHERITED'),
    ('COST_CENTER', 'STREAMLIT', 'INHERITED'),
    ('COST_CENTER', 'APPLICATION', 'INHERITED'),
    ('CRITICALITY', 'DATABASE', 'RECOMMENDED'),
    ('CRITICALITY', 'SCHEMA', 'RECOMMENDED'),
    ('CRITICALITY', 'TABLE', 'INHERITED'),
    ('CRITICALITY', 'VIEW', 'INHERITED'),
    ('CRITICALITY', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('CRITICALITY', 'DYNAMIC_TABLE', 'INHERITED'),
    ('CRITICALITY', 'PIPE', 'INHERITED'),
    ('CRITICALITY', 'TASK', 'INHERITED'),
    ('CRITICALITY', 'STREAM', 'INHERITED'),
    ('CRITICALITY', 'WAREHOUSE', 'INHERITED'),
    ('CRITICALITY', 'APPLICATION', 'INHERITED'),
    ('DATA_LIFECYCLE', 'DATABASE', 'INHERITED'),
    ('DATA_LIFECYCLE', 'SCHEMA', 'RECOMMENDED'),
    ('DATA_LIFECYCLE', 'TABLE', 'RECOMMENDED'),
    ('DATA_LIFECYCLE', 'VIEW', 'INHERITED'),
    ('DATA_LIFECYCLE', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('DATA_LIFECYCLE', 'DYNAMIC_TABLE', 'INHERITED'),
    ('DATA_LIFECYCLE', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_LIFECYCLE', 'STAGE', 'INHERITED'),
    ('DATA_LIFECYCLE', 'PIPE', 'INHERITED'),
    ('DATA_LIFECYCLE', 'TASK', 'INHERITED'),
    ('DATA_LIFECYCLE', 'STREAM', 'INHERITED'),
    ('DATA_LIFECYCLE', 'SHARE', 'INHERITED'),
    ('RETENTION_CLASS', 'DATABASE', 'INHERITED'),
    ('RETENTION_CLASS', 'SCHEMA', 'RECOMMENDED'),
    ('RETENTION_CLASS', 'TABLE', 'INHERITED'),
    ('RETENTION_CLASS', 'VIEW', 'INHERITED'),
    ('RETENTION_CLASS', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('RETENTION_CLASS', 'DYNAMIC_TABLE', 'INHERITED'),
    ('RETENTION_CLASS', 'EXTERNAL_TABLE', 'INHERITED'),
    ('RETENTION_CLASS', 'ICEBERG_TABLE', 'INHERITED'),
    ('RETENTION_CLASS', 'STAGE', 'RECOMMENDED'),
    ('LEGAL_HOLD', 'DATABASE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'SCHEMA', 'OPTIONAL'),
    ('LEGAL_HOLD', 'TABLE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'VIEW', 'OPTIONAL'),
    ('LEGAL_HOLD', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('LEGAL_HOLD', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('LEGAL_HOLD', 'STAGE', 'OPTIONAL'),
    ('REGULATION', 'DATABASE', 'INHERITED'),
    ('REGULATION', 'SCHEMA', 'RECOMMENDED'),
    ('REGULATION', 'TABLE', 'INHERITED'),
    ('REGULATION', 'VIEW', 'INHERITED'),
    ('REGULATION', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('REGULATION', 'DYNAMIC_TABLE', 'INHERITED'),
    ('REGULATION', 'EXTERNAL_TABLE', 'INHERITED'),
    ('REGULATION', 'ICEBERG_TABLE', 'INHERITED'),
    ('REGULATION', 'COLUMN', 'OPTIONAL'),
    ('REGULATION', 'STAGE', 'INHERITED'),
    ('REGULATION', 'SHARE', 'MANDATORY'),
    ('SLA_TIER', 'SCHEMA', 'INHERITED'),
    ('SLA_TIER', 'TABLE', 'INHERITED'),
    ('SLA_TIER', 'VIEW', 'INHERITED'),
    ('SLA_TIER', 'MATERIALIZED_VIEW', 'INHERITED'),
    ('SLA_TIER', 'DYNAMIC_TABLE', 'INHERITED'),
    ('SLA_TIER', 'PIPE', 'INHERITED'),
    ('SLA_TIER', 'TASK', 'INHERITED'),
    ('SLA_TIER', 'STREAM', 'INHERITED'),
    ('SLA_TIER', 'SHARE', 'INHERITED'),
    ('MASKING_REQUIRED', 'TABLE', 'RECOMMENDED'),
    ('MASKING_REQUIRED', 'VIEW', 'OPTIONAL'),
    ('MASKING_REQUIRED', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('MASKING_REQUIRED', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('MASKING_REQUIRED', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('MASKING_REQUIRED', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('MASKING_REQUIRED', 'COLUMN', 'RECOMMENDED'),
    ('ROW_ACCESS_REQUIRED', 'TABLE', 'RECOMMENDED'),
    ('ROW_ACCESS_REQUIRED', 'VIEW', 'RECOMMENDED'),
    ('ROW_ACCESS_REQUIRED', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('ROW_ACCESS_REQUIRED', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('ROW_ACCESS_REQUIRED', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('ROW_ACCESS_REQUIRED', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('DATA_RESIDENCY', 'DATABASE', 'INHERITED'),
    ('DATA_RESIDENCY', 'SCHEMA', 'INHERITED'),
    ('DATA_RESIDENCY', 'TABLE', 'INHERITED'),
    ('DATA_RESIDENCY', 'VIEW', 'INHERITED'),
    ('DATA_RESIDENCY', 'EXTERNAL_TABLE', 'INHERITED'),
    ('DATA_RESIDENCY', 'ICEBERG_TABLE', 'INHERITED'),
    ('DATA_RESIDENCY', 'STAGE', 'INHERITED'),
    ('DATA_RESIDENCY', 'SHARE', 'RECOMMENDED'),
    ('DATA_QUALITY_TIER', 'SCHEMA', 'OPTIONAL'),
    ('DATA_QUALITY_TIER', 'TABLE', 'OPTIONAL'),
    ('DATA_QUALITY_TIER', 'VIEW', 'OPTIONAL'),
    ('DATA_QUALITY_TIER', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('DATA_QUALITY_TIER', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('DATA_QUALITY_TIER', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('SUB_DOMAIN', 'SCHEMA', 'OPTIONAL'),
    ('SUB_DOMAIN', 'TABLE', 'OPTIONAL'),
    ('SUB_DOMAIN', 'VIEW', 'OPTIONAL'),
    ('SUB_DOMAIN', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('SUB_DOMAIN', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('SUB_DOMAIN', 'PIPE', 'OPTIONAL'),
    ('SUB_DOMAIN', 'TASK', 'OPTIONAL'),
    ('SUB_DOMAIN', 'STREAM', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'SCHEMA', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'TABLE', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'VIEW', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'STAGE', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'PIPE', 'OPTIONAL'),
    ('SOURCE_SYSTEM', 'STREAM', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'DATABASE', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'SCHEMA', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'STAGE', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'PIPE', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'TASK', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'INTEGRATION', 'OPTIONAL'),
    ('APPLICATION_OWNER', 'APPLICATION', 'OPTIONAL'),
    ('PLATFORM_OWNER', 'ACCOUNT', 'OPTIONAL'),
    ('PLATFORM_OWNER', 'DATABASE', 'OPTIONAL'),
    ('PLATFORM_OWNER', 'WAREHOUSE', 'OPTIONAL'),
    ('PLATFORM_OWNER', 'ROLE', 'OPTIONAL'),
    ('PLATFORM_OWNER', 'INTEGRATION', 'OPTIONAL'),
    ('PLATFORM_OWNER', 'SHARE', 'OPTIONAL'),
    ('DOMAIN_OWNER', 'DATABASE', 'OPTIONAL'),
    ('DOMAIN_OWNER', 'SCHEMA', 'OPTIONAL'),
    ('DATA_PRODUCT_OWNER', 'SCHEMA', 'OPTIONAL'),
    ('DATA_PRODUCT_OWNER', 'SHARE', 'RECOMMENDED'),
    ('DATA_PRODUCT_OWNER', 'STREAMLIT', 'OPTIONAL'),
    ('DATA_PRODUCT_OWNER', 'APPLICATION', 'OPTIONAL'),
    ('DATA_PRODUCT_TYPE', 'SCHEMA', 'OPTIONAL'),
    ('DATA_PRODUCT_TYPE', 'SHARE', 'OPTIONAL'),
    ('CAPABILITY', 'SCHEMA', 'OPTIONAL'),
    ('CAPABILITY', 'TABLE', 'OPTIONAL'),
    ('CAPABILITY', 'VIEW', 'OPTIONAL'),
    ('CAPABILITY', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('CAPABILITY', 'APPLICATION', 'OPTIONAL'),
    ('PROJECT_CODE', 'DATABASE', 'OPTIONAL'),
    ('PROJECT_CODE', 'SCHEMA', 'OPTIONAL'),
    ('PROJECT_CODE', 'PIPE', 'OPTIONAL'),
    ('PROJECT_CODE', 'TASK', 'OPTIONAL'),
    ('PROJECT_CODE', 'WAREHOUSE', 'OPTIONAL'),
    ('PROJECT_CODE', 'NOTEBOOK', 'OPTIONAL'),
    ('PROJECT_CODE', 'STREAMLIT', 'OPTIONAL'),
    ('COST_ALLOCATION_MODEL', 'DATABASE', 'OPTIONAL'),
    ('COST_ALLOCATION_MODEL', 'SCHEMA', 'OPTIONAL'),
    ('COST_ALLOCATION_MODEL', 'WAREHOUSE', 'RECOMMENDED'),
    ('ENCRYPTION_REQUIRED', 'TABLE', 'OPTIONAL'),
    ('ENCRYPTION_REQUIRED', 'COLUMN', 'OPTIONAL'),
    ('ENCRYPTION_REQUIRED', 'STAGE', 'RECOMMENDED'),
    ('ENCRYPTION_REQUIRED', 'PIPE', 'OPTIONAL'),
    ('ENCRYPTION_REQUIRED', 'INTEGRATION', 'OPTIONAL'),
    ('SHARING_SCOPE', 'DATABASE', 'OPTIONAL'),
    ('SHARING_SCOPE', 'SCHEMA', 'OPTIONAL'),
    ('SHARING_SCOPE', 'TABLE', 'OPTIONAL'),
    ('SHARING_SCOPE', 'VIEW', 'OPTIONAL'),
    ('SHARING_SCOPE', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('SHARING_SCOPE', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('SHARING_SCOPE', 'SHARE', 'RECOMMENDED'),
    ('REFRESH_TYPE', 'TABLE', 'OPTIONAL'),
    ('REFRESH_TYPE', 'VIEW', 'OPTIONAL'),
    ('REFRESH_TYPE', 'MATERIALIZED_VIEW', 'OPTIONAL'),
    ('REFRESH_TYPE', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('REFRESH_TYPE', 'EXTERNAL_TABLE', 'OPTIONAL'),
    ('REFRESH_TYPE', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('REFRESH_TYPE', 'PIPE', 'OPTIONAL'),
    ('REFRESH_TYPE', 'TASK', 'OPTIONAL'),
    ('REFRESH_TYPE', 'STREAM', 'OPTIONAL'),
    ('RPO', 'DATABASE', 'OPTIONAL'),
    ('RPO', 'SCHEMA', 'OPTIONAL'),
    ('RPO', 'TABLE', 'OPTIONAL'),
    ('RPO', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('RPO', 'ICEBERG_TABLE', 'OPTIONAL'),
    ('RTO', 'DATABASE', 'OPTIONAL'),
    ('RTO', 'SCHEMA', 'OPTIONAL'),
    ('RTO', 'TABLE', 'OPTIONAL'),
    ('RTO', 'DYNAMIC_TABLE', 'OPTIONAL'),
    ('RTO', 'ICEBERG_TABLE', 'OPTIONAL')
AS v(c1, c2, c3);


-- TAG_CONDITIONAL_RULE
INSERT INTO TAG_CONDITIONAL_RULE (RULE_ID, DESCRIPTION, SEVERITY, OBJECT_TYPES, PREDICATE, THEN_MANDATORY)
SELECT c1, c2, c3, PARSE_JSON(c4)::ARRAY, PARSE_JSON(c5)::OBJECT, PARSE_JSON(c6)::ARRAY
FROM VALUES
    ('CR-001', 'Any column carrying regulated data must declare masking intent, so that declared-versus-enforced drift is detectable for it.', 'CRITICAL', '["COLUMN"]', '{"DATA_CLASSIFICATION_REGULATORY": ["PII", "SPII", "PHI", "PCI"]}', '["MASKING_REQUIRED"]'),
    ('CR-002', 'Cardholder data requires application-layer encryption in addition to Snowflake''s transparent encryption at rest.', 'CRITICAL', '["TABLE", "COLUMN", "STAGE"]', '{"DATA_CLASSIFICATION_REGULATORY": ["PCI"]}', '["ENCRYPTION_REQUIRED"]'),
    ('CR-003', 'RESTRICTED data must declare row-level access intent; confidentiality at this level is rarely satisfied by column masking alone.', 'HIGH', '["TABLE", "VIEW", "MATERIALIZED_VIEW", "DYNAMIC_TABLE"]', '{"DATA_CLASSIFICATION_ENTERPRISE": ["RESTRICTED"]}', '["ROW_ACCESS_REQUIRED"]'),
    ('CR-004', 'Regulated data needs an accountable data owner and a retention class - without both, neither a DSAR nor a purge can be executed.', 'HIGH', '["SCHEMA", "TABLE", "VIEW"]', '{"DATA_CLASSIFICATION_REGULATORY": ["PII", "SPII", "PHI", "PCI"]}', '["DATA_OWNER", "RETENTION_CLASS"]'),
    ('CR-005', 'Personal and health data must declare residency so replication and cross-region sharing can be evaluated before, not after, the fact.', 'HIGH', '["DATABASE", "SCHEMA", "SHARE"]', '{"DATA_CLASSIFICATION_REGULATORY": ["SPII", "PHI", "PCI"]}', '["DATA_RESIDENCY"]'),
    ('CR-006', 'Business-critical objects must publish RPO and RTO for DR planning.', 'MEDIUM', '["DATABASE", "SCHEMA", "TABLE"]', '{"CRITICALITY": ["CRITICAL"]}', '["RPO", "RTO"]'),
    ('CR-007', 'Data leaving the account always needs a named owner, a classification and an explicit distribution scope. There is no version of a share for which this is optional.', 'CRITICAL', '["SHARE"]', '{}', '["SHARING_SCOPE", "DATA_CLASSIFICATION_ENTERPRISE", "DATA_OWNER", "DATA_PRODUCT"]'),
    ('CR-008', 'Production workloads must name an on-call queue and an SLA commitment. An unroutable production incident is the failure this prevents.', 'MEDIUM', '["SCHEMA", "TASK", "PIPE"]', '{"ENVIRONMENT": ["PRD"]}', '["SUPPORT_GROUP", "SLA_TIER"]'),
    ('CR-009', 'Chargeback settlement posts a journal entry, which needs a GL cost centre code; `department` alone is not a posting key.', 'MEDIUM', '["WAREHOUSE", "DATABASE", "SCHEMA"]', '{"COST_ALLOCATION_MODEL": ["CHARGEBACK"]}', '["COST_CENTER"]')
AS v(c1, c2, c3, c4, c5, c6);


-- TAG_POLICY_BINDING
INSERT INTO TAG_POLICY_BINDING (TAG_NAME, TAG_VALUE, POLICY_KIND, POLICY_NAME, DATA_TYPE, ATTACH_MODE, NOTES)
SELECT c1, c2, c3, c4, c5, c6, c7
FROM VALUES
    ('DATA_CLASSIFICATION_ENTERPRISE', NULL, 'MASKING', 'GOVERNANCE.POLICIES.MP_ENTERPRISE_STRING', 'STRING', 'TAG_ATTACHED', 'Bound to data_classification_enterprise only. data_classification_regulatory deliberately carries no attachment of its own - it is read inside the policy body.'),
    ('DATA_CLASSIFICATION_ENTERPRISE', NULL, 'MASKING', 'GOVERNANCE.POLICIES.MP_ENTERPRISE_NUMBER', 'NUMBER', 'TAG_ATTACHED', 'Bound to data_classification_enterprise only. data_classification_regulatory deliberately carries no attachment of its own - it is read inside the policy body.'),
    ('DATA_CLASSIFICATION_ENTERPRISE', NULL, 'MASKING', 'GOVERNANCE.POLICIES.MP_ENTERPRISE_DATE', 'DATE', 'TAG_ATTACHED', 'Bound to data_classification_enterprise only. data_classification_regulatory deliberately carries no attachment of its own - it is read inside the policy body.'),
    ('DATA_CLASSIFICATION_ENTERPRISE', NULL, 'MASKING', 'GOVERNANCE.POLICIES.MP_ENTERPRISE_TIMESTAMP_NTZ', 'TIMESTAMP_NTZ', 'TAG_ATTACHED', 'Bound to data_classification_enterprise only. data_classification_regulatory deliberately carries no attachment of its own - it is read inside the policy body.'),
    ('DATA_CLASSIFICATION_ENTERPRISE', NULL, 'MASKING', 'GOVERNANCE.POLICIES.MP_ENTERPRISE_VARIANT', 'VARIANT', 'TAG_ATTACHED', 'Bound to data_classification_enterprise only. data_classification_regulatory deliberately carries no attachment of its own - it is read inside the policy body.'),
    ('ROW_ACCESS_REQUIRED', 'YES', 'ROW_ACCESS', 'GOVERNANCE.POLICIES.RAP_OPERATING_COMPANY_SCOPE', NULL, 'RECONCILED', 'Applied by a reconciliation task, not by tag attachment, because Snowflake does not support attaching row access policies to tags. The policy binds to the table''s own OPERATING_COMPANY column; a table declaring the tag without that column is reported as CRITICAL rather than skipped.')
AS v(c1, c2, c3, c4, c5, c6, c7);


-- TAG_CONTRADICTION_RULE
INSERT INTO TAG_CONTRADICTION_RULE (RULE_ID, DESCRIPTION, SEVERITY, IF_TAG, IF_VALUES, THEN_TAG, FORBIDDEN_VALUES)
SELECT c1, c2, c3, c4, PARSE_JSON(c5)::ARRAY, c6, PARSE_JSON(c7)::ARRAY
FROM VALUES
    ('XR-001', 'Regulated data cannot be classified PUBLIC or NONE. This combination is almost always a table that was classified before its contents were understood, and it is the single most dangerous state in the estate: the masking policy reads the enterprise classification and lets the data through in clear.', 'CRITICAL', 'DATA_CLASSIFICATION_REGULATORY', '["PII", "SPII", "PHI", "PCI"]', 'DATA_CLASSIFICATION_ENTERPRISE', '["NONE", "PUBLIC"]'),
    ('XR-002', 'RESTRICTED data cannot be shared beyond the enterprise. Caught before a listing is created rather than after it is discovered.', 'CRITICAL', 'DATA_CLASSIFICATION_ENTERPRISE', '["RESTRICTED"]', 'SHARING_SCOPE', '["PARTNER", "PUBLIC_MARKETPLACE"]'),
    ('XR-003', 'Cardholder data must never sit in a training environment. PCI-DSS scope follows the data, and a TRAINING account is not in the assessed CDE.', 'CRITICAL', 'DATA_CLASSIFICATION_REGULATORY', '["PCI"]', 'ENVIRONMENT', '["TRAINING", "DEV"]'),
    ('XR-004', 'A deprecated or archived object cannot carry a live SLA commitment; consumers reading the catalogue would plan against a promise nobody holds.', 'MEDIUM', 'DATA_LIFECYCLE', '["DEPRECATED", "ARCHIVED", "PENDING_PURGE"]', 'SLA_TIER', '["PLATINUM_15M", "GOLD_1H"]')
AS v(c1, c2, c3, c4, c5, c6, c7);


-- VALUE_PRECEDENCE
INSERT INTO VALUE_PRECEDENCE (TAG_NAME, TAG_VALUE, PRECEDENCE_ORDER)
SELECT c1, c2, c3::NUMBER(3,0)
FROM VALUES
    ('DATA_CLASSIFICATION_REGULATORY', 'PCI', 1),
    ('DATA_CLASSIFICATION_REGULATORY', 'PHI', 2),
    ('DATA_CLASSIFICATION_REGULATORY', 'SPII', 3),
    ('DATA_CLASSIFICATION_REGULATORY', 'PII', 4),
    ('DATA_CLASSIFICATION_REGULATORY', 'NONE', 5),
    ('REGULATION', 'HIPAA', 1),
    ('REGULATION', 'PCI_DSS', 2),
    ('REGULATION', 'NERC_CIP', 3),
    ('REGULATION', 'GLBA', 4),
    ('REGULATION', 'SOX', 5),
    ('REGULATION', 'GDPR', 6),
    ('REGULATION', 'CCPA', 7),
    ('REGULATION', 'FERPA', 8),
    ('REGULATION', 'NONE', 9)
AS v(c1, c2, c3);

COMMIT;

SELECT COUNT(*) AS tags_registered FROM TAG_CATALOG;
